// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	domain "github.com/artmexbet/raibecas/services/documents/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDocumentRepository is an autogenerated mock type for the DocumentRepository type
type MockDocumentRepository struct {
	mock.Mock
}

type MockDocumentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocumentRepository) EXPECT() *MockDocumentRepository_Expecter {
	return &MockDocumentRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx, params
func (_m *MockDocumentRepository) Count(ctx context.Context, params domain.ListDocumentsParams) (int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListDocumentsParams) (int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListDocumentsParams) int); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListDocumentsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockDocumentRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.ListDocumentsParams
func (_e *MockDocumentRepository_Expecter) Count(ctx interface{}, params interface{}) *MockDocumentRepository_Count_Call {
	return &MockDocumentRepository_Count_Call{Call: _e.mock.On("Count", ctx, params)}
}

func (_c *MockDocumentRepository_Count_Call) Run(run func(ctx context.Context, params domain.ListDocumentsParams)) *MockDocumentRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListDocumentsParams))
	})
	return _c
}

func (_c *MockDocumentRepository_Count_Call) Return(_a0 int, _a1 error) *MockDocumentRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_Count_Call) RunAndReturn(run func(context.Context, domain.ListDocumentsParams) (int, error)) *MockDocumentRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, doc
func (_m *MockDocumentRepository) Create(ctx context.Context, doc *domain.Document) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Document) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDocumentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *domain.Document
func (_e *MockDocumentRepository_Expecter) Create(ctx interface{}, doc interface{}) *MockDocumentRepository_Create_Call {
	return &MockDocumentRepository_Create_Call{Call: _e.mock.On("Create", ctx, doc)}
}

func (_c *MockDocumentRepository_Create_Call) Run(run func(ctx context.Context, doc *domain.Document)) *MockDocumentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Document))
	})
	return _c
}

func (_c *MockDocumentRepository_Create_Call) Return(_a0 error) *MockDocumentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Document) error) *MockDocumentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockDocumentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDocumentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDocumentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDocumentRepository_Delete_Call {
	return &MockDocumentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDocumentRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDocumentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDocumentRepository_Delete_Call) Return(_a0 error) *MockDocumentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockDocumentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDocumentRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Document, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Document, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Document); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDocumentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDocumentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDocumentRepository_GetByID_Call {
	return &MockDocumentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDocumentRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDocumentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDocumentRepository_GetByID_Call) Return(_a0 *domain.Document, _a1 error) *MockDocumentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Document, error)) *MockDocumentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, params
func (_m *MockDocumentRepository) List(ctx context.Context, params domain.ListDocumentsParams) ([]domain.Document, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListDocumentsParams) ([]domain.Document, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListDocumentsParams) []domain.Document); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Document)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListDocumentsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDocumentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDocumentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.ListDocumentsParams
func (_e *MockDocumentRepository_Expecter) List(ctx interface{}, params interface{}) *MockDocumentRepository_List_Call {
	return &MockDocumentRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockDocumentRepository_List_Call) Run(run func(ctx context.Context, params domain.ListDocumentsParams)) *MockDocumentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListDocumentsParams))
	})
	return _c
}

func (_c *MockDocumentRepository_List_Call) Return(_a0 []domain.Document, _a1 error) *MockDocumentRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDocumentRepository_List_Call) RunAndReturn(run func(context.Context, domain.ListDocumentsParams) ([]domain.Document, error)) *MockDocumentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, doc
func (_m *MockDocumentRepository) Update(ctx context.Context, doc *domain.Document) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Document) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDocumentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - doc *domain.Document
func (_e *MockDocumentRepository_Expecter) Update(ctx interface{}, doc interface{}) *MockDocumentRepository_Update_Call {
	return &MockDocumentRepository_Update_Call{Call: _e.mock.On("Update", ctx, doc)}
}

func (_c *MockDocumentRepository_Update_Call) Run(run func(ctx context.Context, doc *domain.Document)) *MockDocumentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Document))
	})
	return _c
}

func (_c *MockDocumentRepository_Update_Call) Return(_a0 error) *MockDocumentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Document) error) *MockDocumentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIndexedStatus provides a mock function with given fields: ctx, id, indexed
func (_m *MockDocumentRepository) UpdateIndexedStatus(ctx context.Context, id uuid.UUID, indexed bool) error {
	ret := _m.Called(ctx, id, indexed)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIndexedStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, id, indexed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDocumentRepository_UpdateIndexedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIndexedStatus'
type MockDocumentRepository_UpdateIndexedStatus_Call struct {
	*mock.Call
}

// UpdateIndexedStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - indexed bool
func (_e *MockDocumentRepository_Expecter) UpdateIndexedStatus(ctx interface{}, id interface{}, indexed interface{}) *MockDocumentRepository_UpdateIndexedStatus_Call {
	return &MockDocumentRepository_UpdateIndexedStatus_Call{Call: _e.mock.On("UpdateIndexedStatus", ctx, id, indexed)}
}

func (_c *MockDocumentRepository_UpdateIndexedStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, indexed bool)) *MockDocumentRepository_UpdateIndexedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockDocumentRepository_UpdateIndexedStatus_Call) Return(_a0 error) *MockDocumentRepository_UpdateIndexedStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDocumentRepository_UpdateIndexedStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockDocumentRepository_UpdateIndexedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDocumentRepository creates a new instance of MockDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepository {
	mock := &MockDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
