// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DeleteCover provides a mock function with given fields: ctx, path
func (_m *MockStorage) DeleteCover(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCover")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCover'
type MockStorage_DeleteCover_Call struct {
	*mock.Call
}

// DeleteCover is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) DeleteCover(ctx interface{}, path interface{}) *MockStorage_DeleteCover_Call {
	return &MockStorage_DeleteCover_Call{Call: _e.mock.On("DeleteCover", ctx, path)}
}

func (_c *MockStorage_DeleteCover_Call) Run(run func(ctx context.Context, path string)) *MockStorage_DeleteCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteCover_Call) Return(_a0 error) *MockStorage_DeleteCover_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteCover_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_DeleteCover_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDocument provides a mock function with given fields: ctx, path
func (_m *MockStorage) DeleteDocument(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDocument'
type MockStorage_DeleteDocument_Call struct {
	*mock.Call
}

// DeleteDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) DeleteDocument(ctx interface{}, path interface{}) *MockStorage_DeleteDocument_Call {
	return &MockStorage_DeleteDocument_Call{Call: _e.mock.On("DeleteDocument", ctx, path)}
}

func (_c *MockStorage_DeleteDocument_Call) Run(run func(ctx context.Context, path string)) *MockStorage_DeleteDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteDocument_Call) Return(_a0 error) *MockStorage_DeleteDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteDocument_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_DeleteDocument_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoverPresignedURL provides a mock function with given fields: ctx, path
func (_m *MockStorage) GetCoverPresignedURL(ctx context.Context, path string) (string, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetCoverPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetCoverPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoverPresignedURL'
type MockStorage_GetCoverPresignedURL_Call struct {
	*mock.Call
}

// GetCoverPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) GetCoverPresignedURL(ctx interface{}, path interface{}) *MockStorage_GetCoverPresignedURL_Call {
	return &MockStorage_GetCoverPresignedURL_Call{Call: _e.mock.On("GetCoverPresignedURL", ctx, path)}
}

func (_c *MockStorage_GetCoverPresignedURL_Call) Run(run func(ctx context.Context, path string)) *MockStorage_GetCoverPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetCoverPresignedURL_Call) Return(_a0 string, _a1 error) *MockStorage_GetCoverPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetCoverPresignedURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockStorage_GetCoverPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetDocument provides a mock function with given fields: ctx, path
func (_m *MockStorage) GetDocument(ctx context.Context, path string) ([]byte, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetDocument")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDocument'
type MockStorage_GetDocument_Call struct {
	*mock.Call
}

// GetDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockStorage_Expecter) GetDocument(ctx interface{}, path interface{}) *MockStorage_GetDocument_Call {
	return &MockStorage_GetDocument_Call{Call: _e.mock.On("GetDocument", ctx, path)}
}

func (_c *MockStorage_GetDocument_Call) Run(run func(ctx context.Context, path string)) *MockStorage_GetDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetDocument_Call) Return(_a0 []byte, _a1 error) *MockStorage_GetDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetDocument_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockStorage_GetDocument_Call {
	_c.Call.Return(run)
	return _c
}

// ListVersions provides a mock function with given fields: ctx, documentID
func (_m *MockStorage) ListVersions(ctx context.Context, documentID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, documentID)

	if len(ret) == 0 {
		panic("no return value specified for ListVersions")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, documentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, documentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, documentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_ListVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVersions'
type MockStorage_ListVersions_Call struct {
	*mock.Call
}

// ListVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - documentID uuid.UUID
func (_e *MockStorage_Expecter) ListVersions(ctx interface{}, documentID interface{}) *MockStorage_ListVersions_Call {
	return &MockStorage_ListVersions_Call{Call: _e.mock.On("ListVersions", ctx, documentID)}
}

func (_c *MockStorage_ListVersions_Call) Run(run func(ctx context.Context, documentID uuid.UUID)) *MockStorage_ListVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStorage_ListVersions_Call) Return(_a0 []string, _a1 error) *MockStorage_ListVersions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_ListVersions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockStorage_ListVersions_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCover provides a mock function with given fields: ctx, documentID, data, contentType
func (_m *MockStorage) SaveCover(ctx context.Context, documentID uuid.UUID, data []byte, contentType string) (string, error) {
	ret := _m.Called(ctx, documentID, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for SaveCover")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, string) (string, error)); ok {
		return rf(ctx, documentID, data, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, string) string); ok {
		r0 = rf(ctx, documentID, data, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []byte, string) error); ok {
		r1 = rf(ctx, documentID, data, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_SaveCover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCover'
type MockStorage_SaveCover_Call struct {
	*mock.Call
}

// SaveCover is a helper method to define mock.On call
//   - ctx context.Context
//   - documentID uuid.UUID
//   - data []byte
//   - contentType string
func (_e *MockStorage_Expecter) SaveCover(ctx interface{}, documentID interface{}, data interface{}, contentType interface{}) *MockStorage_SaveCover_Call {
	return &MockStorage_SaveCover_Call{Call: _e.mock.On("SaveCover", ctx, documentID, data, contentType)}
}

func (_c *MockStorage_SaveCover_Call) Run(run func(ctx context.Context, documentID uuid.UUID, data []byte, contentType string)) *MockStorage_SaveCover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockStorage_SaveCover_Call) Return(_a0 string, _a1 error) *MockStorage_SaveCover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_SaveCover_Call) RunAndReturn(run func(context.Context, uuid.UUID, []byte, string) (string, error)) *MockStorage_SaveCover_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDocument provides a mock function with given fields: ctx, documentID, version, content
func (_m *MockStorage) SaveDocument(ctx context.Context, documentID uuid.UUID, version int, content []byte) (string, error) {
	ret := _m.Called(ctx, documentID, version, content)

	if len(ret) == 0 {
		panic("no return value specified for SaveDocument")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, []byte) (string, error)); ok {
		return rf(ctx, documentID, version, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, []byte) string); ok {
		r0 = rf(ctx, documentID, version, content)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, []byte) error); ok {
		r1 = rf(ctx, documentID, version, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_SaveDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDocument'
type MockStorage_SaveDocument_Call struct {
	*mock.Call
}

// SaveDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - documentID uuid.UUID
//   - version int
//   - content []byte
func (_e *MockStorage_Expecter) SaveDocument(ctx interface{}, documentID interface{}, version interface{}, content interface{}) *MockStorage_SaveDocument_Call {
	return &MockStorage_SaveDocument_Call{Call: _e.mock.On("SaveDocument", ctx, documentID, version, content)}
}

func (_c *MockStorage_SaveDocument_Call) Run(run func(ctx context.Context, documentID uuid.UUID, version int, content []byte)) *MockStorage_SaveDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].([]byte))
	})
	return _c
}

func (_c *MockStorage_SaveDocument_Call) Return(_a0 string, _a1 error) *MockStorage_SaveDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_SaveDocument_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, []byte) (string, error)) *MockStorage_SaveDocument_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
