// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwt

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// BlacklistAccessToken provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) BlacklistAccessToken(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _mock.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_BlacklistAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistAccessToken'
type MockTokenStore_BlacklistAccessToken_Call struct {
	*mock.Call
}

// BlacklistAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockTokenStore_Expecter) BlacklistAccessToken(ctx interface{}, jti interface{}, ttl interface{}) *MockTokenStore_BlacklistAccessToken_Call {
	return &MockTokenStore_BlacklistAccessToken_Call{Call: _e.mock.On("BlacklistAccessToken", ctx, jti, ttl)}
}

func (_c *MockTokenStore_BlacklistAccessToken_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockTokenStore_BlacklistAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenStore_BlacklistAccessToken_Call) Return(err error) *MockTokenStore_BlacklistAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_BlacklistAccessToken_Call) RunAndReturn(run func(ctx context.Context, jti string, ttl time.Duration) error) *MockTokenStore_BlacklistAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) GetRefreshToken(ctx context.Context, tokenID string) (*RefreshTokenMetadata, error) {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *RefreshTokenMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*RefreshTokenMetadata, error)); ok {
		return returnFunc(ctx, tokenID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *RefreshTokenMetadata); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RefreshTokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStore_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockTokenStore_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenStore_Expecter) GetRefreshToken(ctx interface{}, tokenID interface{}) *MockTokenStore_GetRefreshToken_Call {
	return &MockTokenStore_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenID)}
}

func (_c *MockTokenStore_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenStore_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_GetRefreshToken_Call) Return(refreshTokenMetadata *RefreshTokenMetadata, err error) *MockTokenStore_GetRefreshToken_Call {
	_c.Call.Return(refreshTokenMetadata, err)
	return _c
}

func (_c *MockTokenStore_GetRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) (*RefreshTokenMetadata, error)) *MockTokenStore_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenFamily provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) GetTokenFamily(ctx context.Context, tokenFamily string) ([]*RefreshTokenMetadata, error) {
	ret := _mock.Called(ctx, tokenFamily)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenFamily")
	}

	var r0 []*RefreshTokenMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*RefreshTokenMetadata, error)); ok {
		return returnFunc(ctx, tokenFamily)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*RefreshTokenMetadata); ok {
		r0 = returnFunc(ctx, tokenFamily)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*RefreshTokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenFamily)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStore_GetTokenFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenFamily'
type MockTokenStore_GetTokenFamily_Call struct {
	*mock.Call
}

// GetTokenFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenFamily string
func (_e *MockTokenStore_Expecter) GetTokenFamily(ctx interface{}, tokenFamily interface{}) *MockTokenStore_GetTokenFamily_Call {
	return &MockTokenStore_GetTokenFamily_Call{Call: _e.mock.On("GetTokenFamily", ctx, tokenFamily)}
}

func (_c *MockTokenStore_GetTokenFamily_Call) Run(run func(ctx context.Context, tokenFamily string)) *MockTokenStore_GetTokenFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_GetTokenFamily_Call) Return(refreshTokenMetadatas []*RefreshTokenMetadata, err error) *MockTokenStore_GetTokenFamily_Call {
	_c.Call.Return(refreshTokenMetadatas, err)
	return _c
}

func (_c *MockTokenStore_GetTokenFamily_Call) RunAndReturn(run func(ctx context.Context, tokenFamily string) ([]*RefreshTokenMetadata, error)) *MockTokenStore_GetTokenFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDevices provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) GetUserDevices(ctx context.Context, userID uuid.UUID) ([]string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDevices")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStore_GetUserDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDevices'
type MockTokenStore_GetUserDevices_Call struct {
	*mock.Call
}

// GetUserDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenStore_Expecter) GetUserDevices(ctx interface{}, userID interface{}) *MockTokenStore_GetUserDevices_Call {
	return &MockTokenStore_GetUserDevices_Call{Call: _e.mock.On("GetUserDevices", ctx, userID)}
}

func (_c *MockTokenStore_GetUserDevices_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenStore_GetUserDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_GetUserDevices_Call) Return(strings []string, err error) *MockTokenStore_GetUserDevices_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTokenStore_GetUserDevices_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]string, error)) *MockTokenStore_GetUserDevices_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccessTokenBlacklisted provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) IsAccessTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	ret := _mock.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsAccessTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, jti)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenStore_IsAccessTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccessTokenBlacklisted'
type MockTokenStore_IsAccessTokenBlacklisted_Call struct {
	*mock.Call
}

// IsAccessTokenBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenStore_Expecter) IsAccessTokenBlacklisted(ctx interface{}, jti interface{}) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	return &MockTokenStore_IsAccessTokenBlacklisted_Call{Call: _e.mock.On("IsAccessTokenBlacklisted", ctx, jti)}
}

func (_c *MockTokenStore_IsAccessTokenBlacklisted_Call) Run(run func(ctx context.Context, jti string)) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_IsAccessTokenBlacklisted_Call) Return(b bool, err error) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTokenStore_IsAccessTokenBlacklisted_Call) RunAndReturn(run func(ctx context.Context, jti string) (bool, error)) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserTokens provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_RevokeAllUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserTokens'
type MockTokenStore_RevokeAllUserTokens_Call struct {
	*mock.Call
}

// RevokeAllUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenStore_Expecter) RevokeAllUserTokens(ctx interface{}, userID interface{}) *MockTokenStore_RevokeAllUserTokens_Call {
	return &MockTokenStore_RevokeAllUserTokens_Call{Call: _e.mock.On("RevokeAllUserTokens", ctx, userID)}
}

func (_c *MockTokenStore_RevokeAllUserTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenStore_RevokeAllUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_RevokeAllUserTokens_Call) Return(err error) *MockTokenStore_RevokeAllUserTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_RevokeAllUserTokens_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockTokenStore_RevokeAllUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeDeviceTokens provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) RevokeDeviceTokens(ctx context.Context, userID uuid.UUID, deviceID string) error {
	ret := _mock.Called(ctx, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeDeviceTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, deviceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_RevokeDeviceTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeDeviceTokens'
type MockTokenStore_RevokeDeviceTokens_Call struct {
	*mock.Call
}

// RevokeDeviceTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deviceID string
func (_e *MockTokenStore_Expecter) RevokeDeviceTokens(ctx interface{}, userID interface{}, deviceID interface{}) *MockTokenStore_RevokeDeviceTokens_Call {
	return &MockTokenStore_RevokeDeviceTokens_Call{Call: _e.mock.On("RevokeDeviceTokens", ctx, userID, deviceID)}
}

func (_c *MockTokenStore_RevokeDeviceTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID, deviceID string)) *MockTokenStore_RevokeDeviceTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenStore_RevokeDeviceTokens_Call) Return(err error) *MockTokenStore_RevokeDeviceTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_RevokeDeviceTokens_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, deviceID string) error) *MockTokenStore_RevokeDeviceTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) RevokeRefreshToken(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockTokenStore_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenStore_Expecter) RevokeRefreshToken(ctx interface{}, tokenID interface{}) *MockTokenStore_RevokeRefreshToken_Call {
	return &MockTokenStore_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenID)}
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) Return(err error) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshTokenFamily provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) RevokeRefreshTokenFamily(ctx context.Context, tokenFamily string) error {
	ret := _mock.Called(ctx, tokenFamily)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshTokenFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenFamily)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_RevokeRefreshTokenFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshTokenFamily'
type MockTokenStore_RevokeRefreshTokenFamily_Call struct {
	*mock.Call
}

// RevokeRefreshTokenFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenFamily string
func (_e *MockTokenStore_Expecter) RevokeRefreshTokenFamily(ctx interface{}, tokenFamily interface{}) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	return &MockTokenStore_RevokeRefreshTokenFamily_Call{Call: _e.mock.On("RevokeRefreshTokenFamily", ctx, tokenFamily)}
}

func (_c *MockTokenStore_RevokeRefreshTokenFamily_Call) Run(run func(ctx context.Context, tokenFamily string)) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenStore_RevokeRefreshTokenFamily_Call) Return(err error) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_RevokeRefreshTokenFamily_Call) RunAndReturn(run func(ctx context.Context, tokenFamily string) error) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function for the type MockTokenStore
func (_mock *MockTokenStore) StoreRefreshToken(ctx context.Context, metadata *RefreshTokenMetadata, ttl time.Duration) error {
	ret := _mock.Called(ctx, metadata, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *RefreshTokenMetadata, time.Duration) error); ok {
		r0 = returnFunc(ctx, metadata, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenStore_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockTokenStore_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *RefreshTokenMetadata
//   - ttl time.Duration
func (_e *MockTokenStore_Expecter) StoreRefreshToken(ctx interface{}, metadata interface{}, ttl interface{}) *MockTokenStore_StoreRefreshToken_Call {
	return &MockTokenStore_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, metadata, ttl)}
}

func (_c *MockTokenStore_StoreRefreshToken_Call) Run(run func(ctx context.Context, metadata *RefreshTokenMetadata, ttl time.Duration)) *MockTokenStore_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RefreshTokenMetadata
		if args[1] != nil {
			arg1 = args[1].(*RefreshTokenMetadata)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenStore_StoreRefreshToken_Call) Return(err error) *MockTokenStore_StoreRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenStore_StoreRefreshToken_Call) RunAndReturn(run func(ctx context.Context, metadata *RefreshTokenMetadata, ttl time.Duration) error) *MockTokenStore_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateAccessToken(metadata *TokenMetadata) (string, *AccessTokenClaims, error) {
	ret := _mock.Called(metadata)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 *AccessTokenClaims
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) (string, *AccessTokenClaims, error)); ok {
		return returnFunc(metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) string); ok {
		r0 = returnFunc(metadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*TokenMetadata) *AccessTokenClaims); ok {
		r1 = returnFunc(metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*TokenMetadata) error); ok {
		r2 = returnFunc(metadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenGenerator_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenGenerator_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - metadata *TokenMetadata
func (_e *MockTokenGenerator_Expecter) GenerateAccessToken(metadata interface{}) *MockTokenGenerator_GenerateAccessToken_Call {
	return &MockTokenGenerator_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", metadata)}
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) Run(run func(metadata *TokenMetadata)) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TokenMetadata
		if args[0] != nil {
			arg0 = args[0].(*TokenMetadata)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) Return(s string, accessTokenClaims *AccessTokenClaims, err error) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Return(s, accessTokenClaims, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateAccessToken_Call) RunAndReturn(run func(metadata *TokenMetadata) (string, *AccessTokenClaims, error)) *MockTokenGenerator_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GenerateRefreshToken(metadata *TokenMetadata) (string, *RefreshTokenMetadata, error) {
	ret := _mock.Called(metadata)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 *RefreshTokenMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) (string, *RefreshTokenMetadata, error)); ok {
		return returnFunc(metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) string); ok {
		r0 = returnFunc(metadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*TokenMetadata) *RefreshTokenMetadata); ok {
		r1 = returnFunc(metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*RefreshTokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*TokenMetadata) error); ok {
		r2 = returnFunc(metadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenGenerator_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenGenerator_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - metadata *TokenMetadata
func (_e *MockTokenGenerator_Expecter) GenerateRefreshToken(metadata interface{}) *MockTokenGenerator_GenerateRefreshToken_Call {
	return &MockTokenGenerator_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", metadata)}
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) Run(run func(metadata *TokenMetadata)) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TokenMetadata
		if args[0] != nil {
			arg0 = args[0].(*TokenMetadata)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) Return(s string, refreshTokenMetadata *RefreshTokenMetadata, err error) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Return(s, refreshTokenMetadata, err)
	return _c
}

func (_c *MockTokenGenerator_GenerateRefreshToken_Call) RunAndReturn(run func(metadata *TokenMetadata) (string, *RefreshTokenMetadata, error)) *MockTokenGenerator_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenTTL provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) GetRefreshTokenTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenGenerator_GetRefreshTokenTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenTTL'
type MockTokenGenerator_GetRefreshTokenTTL_Call struct {
	*mock.Call
}

// GetRefreshTokenTTL is a helper method to define mock.On call
func (_e *MockTokenGenerator_Expecter) GetRefreshTokenTTL() *MockTokenGenerator_GetRefreshTokenTTL_Call {
	return &MockTokenGenerator_GetRefreshTokenTTL_Call{Call: _e.mock.On("GetRefreshTokenTTL")}
}

func (_c *MockTokenGenerator_GetRefreshTokenTTL_Call) Run(run func()) *MockTokenGenerator_GetRefreshTokenTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenGenerator_GetRefreshTokenTTL_Call) Return(duration time.Duration) *MockTokenGenerator_GetRefreshTokenTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenGenerator_GetRefreshTokenTTL_Call) RunAndReturn(run func() time.Duration) *MockTokenGenerator_GetRefreshTokenTTL_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function for the type MockTokenGenerator
func (_mock *MockTokenGenerator) StoreRefreshToken(ctx context.Context, metadata *RefreshTokenMetadata) error {
	ret := _mock.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *RefreshTokenMetadata) error); ok {
		r0 = returnFunc(ctx, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenGenerator_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockTokenGenerator_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *RefreshTokenMetadata
func (_e *MockTokenGenerator_Expecter) StoreRefreshToken(ctx interface{}, metadata interface{}) *MockTokenGenerator_StoreRefreshToken_Call {
	return &MockTokenGenerator_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, metadata)}
}

func (_c *MockTokenGenerator_StoreRefreshToken_Call) Run(run func(ctx context.Context, metadata *RefreshTokenMetadata)) *MockTokenGenerator_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RefreshTokenMetadata
		if args[1] != nil {
			arg1 = args[1].(*RefreshTokenMetadata)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenGenerator_StoreRefreshToken_Call) Return(err error) *MockTokenGenerator_StoreRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenGenerator_StoreRefreshToken_Call) RunAndReturn(run func(ctx context.Context, metadata *RefreshTokenMetadata) error) *MockTokenGenerator_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccessToken provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) ValidateAccessToken(ctx context.Context, token string, expectedFingerprint string) (*ValidationResult, error) {
	ret := _mock.Called(ctx, token, expectedFingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *ValidationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ValidationResult, error)); ok {
		return returnFunc(ctx, token, expectedFingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ValidationResult); ok {
		r0 = returnFunc(ctx, token, expectedFingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ValidationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, expectedFingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenValidator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - expectedFingerprint string
func (_e *MockTokenValidator_Expecter) ValidateAccessToken(ctx interface{}, token interface{}, expectedFingerprint interface{}) *MockTokenValidator_ValidateAccessToken_Call {
	return &MockTokenValidator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, token, expectedFingerprint)}
}

func (_c *MockTokenValidator_ValidateAccessToken_Call) Run(run func(ctx context.Context, token string, expectedFingerprint string)) *MockTokenValidator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateAccessToken_Call) Return(validationResult *ValidationResult, err error) *MockTokenValidator_ValidateAccessToken_Call {
	_c.Call.Return(validationResult, err)
	return _c
}

func (_c *MockTokenValidator_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string, expectedFingerprint string) (*ValidationResult, error)) *MockTokenValidator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) ValidateRefreshToken(ctx context.Context, tokenID string, expectedFingerprint string) (*RefreshTokenMetadata, error) {
	ret := _mock.Called(ctx, tokenID, expectedFingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *RefreshTokenMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*RefreshTokenMetadata, error)); ok {
		return returnFunc(ctx, tokenID, expectedFingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *RefreshTokenMetadata); ok {
		r0 = returnFunc(ctx, tokenID, expectedFingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RefreshTokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tokenID, expectedFingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenValidator_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - expectedFingerprint string
func (_e *MockTokenValidator_Expecter) ValidateRefreshToken(ctx interface{}, tokenID interface{}, expectedFingerprint interface{}) *MockTokenValidator_ValidateRefreshToken_Call {
	return &MockTokenValidator_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, tokenID, expectedFingerprint)}
}

func (_c *MockTokenValidator_ValidateRefreshToken_Call) Run(run func(ctx context.Context, tokenID string, expectedFingerprint string)) *MockTokenValidator_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateRefreshToken_Call) Return(refreshTokenMetadata *RefreshTokenMetadata, err error) *MockTokenValidator_ValidateRefreshToken_Call {
	_c.Call.Return(refreshTokenMetadata, err)
	return _c
}

func (_c *MockTokenValidator_ValidateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string, expectedFingerprint string) (*RefreshTokenMetadata, error)) *MockTokenValidator_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateAccessToken(metadata *TokenMetadata) (string, *AccessTokenClaims, error) {
	ret := _mock.Called(metadata)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 *AccessTokenClaims
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) (string, *AccessTokenClaims, error)); ok {
		return returnFunc(metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) string); ok {
		r0 = returnFunc(metadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*TokenMetadata) *AccessTokenClaims); ok {
		r1 = returnFunc(metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*TokenMetadata) error); ok {
		r2 = returnFunc(metadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenManager_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenManager_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - metadata *TokenMetadata
func (_e *MockTokenManager_Expecter) GenerateAccessToken(metadata interface{}) *MockTokenManager_GenerateAccessToken_Call {
	return &MockTokenManager_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", metadata)}
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Run(run func(metadata *TokenMetadata)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TokenMetadata
		if args[0] != nil {
			arg0 = args[0].(*TokenMetadata)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Return(s string, accessTokenClaims *AccessTokenClaims, err error) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(s, accessTokenClaims, err)
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) RunAndReturn(run func(metadata *TokenMetadata) (string, *AccessTokenClaims, error)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GenerateRefreshToken(metadata *TokenMetadata) (string, *RefreshTokenMetadata, error) {
	ret := _mock.Called(metadata)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 *RefreshTokenMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) (string, *RefreshTokenMetadata, error)); ok {
		return returnFunc(metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(*TokenMetadata) string); ok {
		r0 = returnFunc(metadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*TokenMetadata) *RefreshTokenMetadata); ok {
		r1 = returnFunc(metadata)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*RefreshTokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(*TokenMetadata) error); ok {
		r2 = returnFunc(metadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenManager_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenManager_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - metadata *TokenMetadata
func (_e *MockTokenManager_Expecter) GenerateRefreshToken(metadata interface{}) *MockTokenManager_GenerateRefreshToken_Call {
	return &MockTokenManager_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", metadata)}
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) Run(run func(metadata *TokenMetadata)) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TokenMetadata
		if args[0] != nil {
			arg0 = args[0].(*TokenMetadata)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) Return(s string, refreshTokenMetadata *RefreshTokenMetadata, err error) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Return(s, refreshTokenMetadata, err)
	return _c
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) RunAndReturn(run func(metadata *TokenMetadata) (string, *RefreshTokenMetadata, error)) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenTTL provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) GetRefreshTokenTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockTokenManager_GetRefreshTokenTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenTTL'
type MockTokenManager_GetRefreshTokenTTL_Call struct {
	*mock.Call
}

// GetRefreshTokenTTL is a helper method to define mock.On call
func (_e *MockTokenManager_Expecter) GetRefreshTokenTTL() *MockTokenManager_GetRefreshTokenTTL_Call {
	return &MockTokenManager_GetRefreshTokenTTL_Call{Call: _e.mock.On("GetRefreshTokenTTL")}
}

func (_c *MockTokenManager_GetRefreshTokenTTL_Call) Run(run func()) *MockTokenManager_GetRefreshTokenTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenManager_GetRefreshTokenTTL_Call) Return(duration time.Duration) *MockTokenManager_GetRefreshTokenTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockTokenManager_GetRefreshTokenTTL_Call) RunAndReturn(run func() time.Duration) *MockTokenManager_GetRefreshTokenTTL_Call {
	_c.Call.Return(run)
	return _c
}

// IntrospectAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) IntrospectAccessToken(ctx context.Context, token string) (*AccessTokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IntrospectAccessToken")
	}

	var r0 *AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*AccessTokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *AccessTokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_IntrospectAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntrospectAccessToken'
type MockTokenManager_IntrospectAccessToken_Call struct {
	*mock.Call
}

// IntrospectAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenManager_Expecter) IntrospectAccessToken(ctx interface{}, token interface{}) *MockTokenManager_IntrospectAccessToken_Call {
	return &MockTokenManager_IntrospectAccessToken_Call{Call: _e.mock.On("IntrospectAccessToken", ctx, token)}
}

func (_c *MockTokenManager_IntrospectAccessToken_Call) Run(run func(ctx context.Context, token string)) *MockTokenManager_IntrospectAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_IntrospectAccessToken_Call) Return(accessTokenClaims *AccessTokenClaims, err error) *MockTokenManager_IntrospectAccessToken_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockTokenManager_IntrospectAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*AccessTokenClaims, error)) *MockTokenManager_IntrospectAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) RevokeAccessToken(ctx context.Context, jti string) error {
	ret := _mock.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAccessToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, jti)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenManager_RevokeAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAccessToken'
type MockTokenManager_RevokeAccessToken_Call struct {
	*mock.Call
}

// RevokeAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenManager_Expecter) RevokeAccessToken(ctx interface{}, jti interface{}) *MockTokenManager_RevokeAccessToken_Call {
	return &MockTokenManager_RevokeAccessToken_Call{Call: _e.mock.On("RevokeAccessToken", ctx, jti)}
}

func (_c *MockTokenManager_RevokeAccessToken_Call) Run(run func(ctx context.Context, jti string)) *MockTokenManager_RevokeAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_RevokeAccessToken_Call) Return(err error) *MockTokenManager_RevokeAccessToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenManager_RevokeAccessToken_Call) RunAndReturn(run func(ctx context.Context, jti string) error) *MockTokenManager_RevokeAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserTokens provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenManager_RevokeAllUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserTokens'
type MockTokenManager_RevokeAllUserTokens_Call struct {
	*mock.Call
}

// RevokeAllUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenManager_Expecter) RevokeAllUserTokens(ctx interface{}, userID interface{}) *MockTokenManager_RevokeAllUserTokens_Call {
	return &MockTokenManager_RevokeAllUserTokens_Call{Call: _e.mock.On("RevokeAllUserTokens", ctx, userID)}
}

func (_c *MockTokenManager_RevokeAllUserTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenManager_RevokeAllUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_RevokeAllUserTokens_Call) Return(err error) *MockTokenManager_RevokeAllUserTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenManager_RevokeAllUserTokens_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockTokenManager_RevokeAllUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) RevokeRefreshToken(ctx context.Context, tokenID string) error {
	ret := _mock.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenManager_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockTokenManager_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenManager_Expecter) RevokeRefreshToken(ctx interface{}, tokenID interface{}) *MockTokenManager_RevokeRefreshToken_Call {
	return &MockTokenManager_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenID)}
}

func (_c *MockTokenManager_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenManager_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_RevokeRefreshToken_Call) Return(err error) *MockTokenManager_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenManager_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string) error) *MockTokenManager_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RotateRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) RotateRefreshToken(ctx context.Context, oldTokenID string, metadata *TokenMetadata) (string, string, error) {
	ret := _mock.Called(ctx, oldTokenID, metadata)

	if len(ret) == 0 {
		panic("no return value specified for RotateRefreshToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *TokenMetadata) (string, string, error)); ok {
		return returnFunc(ctx, oldTokenID, metadata)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *TokenMetadata) string); ok {
		r0 = returnFunc(ctx, oldTokenID, metadata)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *TokenMetadata) string); ok {
		r1 = returnFunc(ctx, oldTokenID, metadata)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *TokenMetadata) error); ok {
		r2 = returnFunc(ctx, oldTokenID, metadata)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockTokenManager_RotateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateRefreshToken'
type MockTokenManager_RotateRefreshToken_Call struct {
	*mock.Call
}

// RotateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - oldTokenID string
//   - metadata *TokenMetadata
func (_e *MockTokenManager_Expecter) RotateRefreshToken(ctx interface{}, oldTokenID interface{}, metadata interface{}) *MockTokenManager_RotateRefreshToken_Call {
	return &MockTokenManager_RotateRefreshToken_Call{Call: _e.mock.On("RotateRefreshToken", ctx, oldTokenID, metadata)}
}

func (_c *MockTokenManager_RotateRefreshToken_Call) Run(run func(ctx context.Context, oldTokenID string, metadata *TokenMetadata)) *MockTokenManager_RotateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *TokenMetadata
		if args[2] != nil {
			arg2 = args[2].(*TokenMetadata)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenManager_RotateRefreshToken_Call) Return(accessToken string, refreshToken string, err error) *MockTokenManager_RotateRefreshToken_Call {
	_c.Call.Return(accessToken, refreshToken, err)
	return _c
}

func (_c *MockTokenManager_RotateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, oldTokenID string, metadata *TokenMetadata) (string, string, error)) *MockTokenManager_RotateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) StoreRefreshToken(ctx context.Context, metadata *RefreshTokenMetadata) error {
	ret := _mock.Called(ctx, metadata)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *RefreshTokenMetadata) error); ok {
		r0 = returnFunc(ctx, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTokenManager_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockTokenManager_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *RefreshTokenMetadata
func (_e *MockTokenManager_Expecter) StoreRefreshToken(ctx interface{}, metadata interface{}) *MockTokenManager_StoreRefreshToken_Call {
	return &MockTokenManager_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, metadata)}
}

func (_c *MockTokenManager_StoreRefreshToken_Call) Run(run func(ctx context.Context, metadata *RefreshTokenMetadata)) *MockTokenManager_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *RefreshTokenMetadata
		if args[1] != nil {
			arg1 = args[1].(*RefreshTokenMetadata)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTokenManager_StoreRefreshToken_Call) Return(err error) *MockTokenManager_StoreRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTokenManager_StoreRefreshToken_Call) RunAndReturn(run func(ctx context.Context, metadata *RefreshTokenMetadata) error) *MockTokenManager_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) ValidateAccessToken(ctx context.Context, token string, expectedFingerprint string) (*ValidationResult, error) {
	ret := _mock.Called(ctx, token, expectedFingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *ValidationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*ValidationResult, error)); ok {
		return returnFunc(ctx, token, expectedFingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *ValidationResult); ok {
		r0 = returnFunc(ctx, token, expectedFingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ValidationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, expectedFingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenManager_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - expectedFingerprint string
func (_e *MockTokenManager_Expecter) ValidateAccessToken(ctx interface{}, token interface{}, expectedFingerprint interface{}) *MockTokenManager_ValidateAccessToken_Call {
	return &MockTokenManager_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", ctx, token, expectedFingerprint)}
}

func (_c *MockTokenManager_ValidateAccessToken_Call) Run(run func(ctx context.Context, token string, expectedFingerprint string)) *MockTokenManager_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenManager_ValidateAccessToken_Call) Return(validationResult *ValidationResult, err error) *MockTokenManager_ValidateAccessToken_Call {
	_c.Call.Return(validationResult, err)
	return _c
}

func (_c *MockTokenManager_ValidateAccessToken_Call) RunAndReturn(run func(ctx context.Context, token string, expectedFingerprint string) (*ValidationResult, error)) *MockTokenManager_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) ValidateRefreshToken(ctx context.Context, tokenID string, expectedFingerprint string) (*RefreshTokenMetadata, error) {
	ret := _mock.Called(ctx, tokenID, expectedFingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *RefreshTokenMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*RefreshTokenMetadata, error)); ok {
		return returnFunc(ctx, tokenID, expectedFingerprint)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *RefreshTokenMetadata); ok {
		r0 = returnFunc(ctx, tokenID, expectedFingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RefreshTokenMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tokenID, expectedFingerprint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenManager_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - expectedFingerprint string
func (_e *MockTokenManager_Expecter) ValidateRefreshToken(ctx interface{}, tokenID interface{}, expectedFingerprint interface{}) *MockTokenManager_ValidateRefreshToken_Call {
	return &MockTokenManager_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, tokenID, expectedFingerprint)}
}

func (_c *MockTokenManager_ValidateRefreshToken_Call) Run(run func(ctx context.Context, tokenID string, expectedFingerprint string)) *MockTokenManager_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenManager_ValidateRefreshToken_Call) Return(refreshTokenMetadata *RefreshTokenMetadata, err error) *MockTokenManager_ValidateRefreshToken_Call {
	_c.Call.Return(refreshTokenMetadata, err)
	return _c
}

func (_c *MockTokenManager_ValidateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenID string, expectedFingerprint string) (*RefreshTokenMetadata, error)) *MockTokenManager_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
