// Code generated by mockery. DO NOT EDIT.

package jwt

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenStore is an autogenerated mock type for the TokenStore type
type MockTokenStore struct {
	mock.Mock
}

type MockTokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenStore) EXPECT() *MockTokenStore_Expecter {
	return &MockTokenStore_Expecter{mock: &_m.Mock}
}

// BlacklistAccessToken provides a mock function with given fields: ctx, jti, ttl
func (_m *MockTokenStore) BlacklistAccessToken(ctx context.Context, jti string, ttl time.Duration) error {
	ret := _m.Called(ctx, jti, ttl)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(ctx, jti, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_BlacklistAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistAccessToken'
type MockTokenStore_BlacklistAccessToken_Call struct {
	*mock.Call
}

// BlacklistAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttl time.Duration
func (_e *MockTokenStore_Expecter) BlacklistAccessToken(ctx interface{}, jti interface{}, ttl interface{}) *MockTokenStore_BlacklistAccessToken_Call {
	return &MockTokenStore_BlacklistAccessToken_Call{Call: _e.mock.On("BlacklistAccessToken", ctx, jti, ttl)}
}

func (_c *MockTokenStore_BlacklistAccessToken_Call) Run(run func(ctx context.Context, jti string, ttl time.Duration)) *MockTokenStore_BlacklistAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockTokenStore_BlacklistAccessToken_Call) Return(_a0 error) *MockTokenStore_BlacklistAccessToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_BlacklistAccessToken_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockTokenStore_BlacklistAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenID
func (_m *MockTokenStore) GetRefreshToken(ctx context.Context, tokenID string) (*RefreshTokenMetadata, error) {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *RefreshTokenMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*RefreshTokenMetadata, error)); ok {
		return rf(ctx, tokenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *RefreshTokenMetadata); ok {
		r0 = rf(ctx, tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RefreshTokenMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockTokenStore_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenStore_Expecter) GetRefreshToken(ctx interface{}, tokenID interface{}) *MockTokenStore_GetRefreshToken_Call {
	return &MockTokenStore_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenID)}
}

func (_c *MockTokenStore_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenStore_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_GetRefreshToken_Call) Return(_a0 *RefreshTokenMetadata, _a1 error) *MockTokenStore_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*RefreshTokenMetadata, error)) *MockTokenStore_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenFamily provides a mock function with given fields: ctx, tokenFamily
func (_m *MockTokenStore) GetTokenFamily(ctx context.Context, tokenFamily string) ([]*RefreshTokenMetadata, error) {
	ret := _m.Called(ctx, tokenFamily)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenFamily")
	}

	var r0 []*RefreshTokenMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*RefreshTokenMetadata, error)); ok {
		return rf(ctx, tokenFamily)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*RefreshTokenMetadata); ok {
		r0 = rf(ctx, tokenFamily)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*RefreshTokenMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenFamily)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_GetTokenFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenFamily'
type MockTokenStore_GetTokenFamily_Call struct {
	*mock.Call
}

// GetTokenFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenFamily string
func (_e *MockTokenStore_Expecter) GetTokenFamily(ctx interface{}, tokenFamily interface{}) *MockTokenStore_GetTokenFamily_Call {
	return &MockTokenStore_GetTokenFamily_Call{Call: _e.mock.On("GetTokenFamily", ctx, tokenFamily)}
}

func (_c *MockTokenStore_GetTokenFamily_Call) Run(run func(ctx context.Context, tokenFamily string)) *MockTokenStore_GetTokenFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_GetTokenFamily_Call) Return(_a0 []*RefreshTokenMetadata, _a1 error) *MockTokenStore_GetTokenFamily_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_GetTokenFamily_Call) RunAndReturn(run func(context.Context, string) ([]*RefreshTokenMetadata, error)) *MockTokenStore_GetTokenFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDevices provides a mock function with given fields: ctx, userID
func (_m *MockTokenStore) GetUserDevices(ctx context.Context, userID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDevices")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_GetUserDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDevices'
type MockTokenStore_GetUserDevices_Call struct {
	*mock.Call
}

// GetUserDevices is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenStore_Expecter) GetUserDevices(ctx interface{}, userID interface{}) *MockTokenStore_GetUserDevices_Call {
	return &MockTokenStore_GetUserDevices_Call{Call: _e.mock.On("GetUserDevices", ctx, userID)}
}

func (_c *MockTokenStore_GetUserDevices_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenStore_GetUserDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenStore_GetUserDevices_Call) Return(_a0 []string, _a1 error) *MockTokenStore_GetUserDevices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_GetUserDevices_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockTokenStore_GetUserDevices_Call {
	_c.Call.Return(run)
	return _c
}

// IsAccessTokenBlacklisted provides a mock function with given fields: ctx, jti
func (_m *MockTokenStore) IsAccessTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsAccessTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenStore_IsAccessTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAccessTokenBlacklisted'
type MockTokenStore_IsAccessTokenBlacklisted_Call struct {
	*mock.Call
}

// IsAccessTokenBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockTokenStore_Expecter) IsAccessTokenBlacklisted(ctx interface{}, jti interface{}) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	return &MockTokenStore_IsAccessTokenBlacklisted_Call{Call: _e.mock.On("IsAccessTokenBlacklisted", ctx, jti)}
}

func (_c *MockTokenStore_IsAccessTokenBlacklisted_Call) Run(run func(ctx context.Context, jti string)) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_IsAccessTokenBlacklisted_Call) Return(_a0 bool, _a1 error) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenStore_IsAccessTokenBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenStore_IsAccessTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserTokens provides a mock function with given fields: ctx, userID
func (_m *MockTokenStore) RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RevokeAllUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserTokens'
type MockTokenStore_RevokeAllUserTokens_Call struct {
	*mock.Call
}

// RevokeAllUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenStore_Expecter) RevokeAllUserTokens(ctx interface{}, userID interface{}) *MockTokenStore_RevokeAllUserTokens_Call {
	return &MockTokenStore_RevokeAllUserTokens_Call{Call: _e.mock.On("RevokeAllUserTokens", ctx, userID)}
}

func (_c *MockTokenStore_RevokeAllUserTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenStore_RevokeAllUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenStore_RevokeAllUserTokens_Call) Return(_a0 error) *MockTokenStore_RevokeAllUserTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RevokeAllUserTokens_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTokenStore_RevokeAllUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeDeviceTokens provides a mock function with given fields: ctx, userID, deviceID
func (_m *MockTokenStore) RevokeDeviceTokens(ctx context.Context, userID uuid.UUID, deviceID string) error {
	ret := _m.Called(ctx, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeDeviceTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RevokeDeviceTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeDeviceTokens'
type MockTokenStore_RevokeDeviceTokens_Call struct {
	*mock.Call
}

// RevokeDeviceTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - deviceID string
func (_e *MockTokenStore_Expecter) RevokeDeviceTokens(ctx interface{}, userID interface{}, deviceID interface{}) *MockTokenStore_RevokeDeviceTokens_Call {
	return &MockTokenStore_RevokeDeviceTokens_Call{Call: _e.mock.On("RevokeDeviceTokens", ctx, userID, deviceID)}
}

func (_c *MockTokenStore_RevokeDeviceTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID, deviceID string)) *MockTokenStore_RevokeDeviceTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockTokenStore_RevokeDeviceTokens_Call) Return(_a0 error) *MockTokenStore_RevokeDeviceTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RevokeDeviceTokens_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockTokenStore_RevokeDeviceTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenID
func (_m *MockTokenStore) RevokeRefreshToken(ctx context.Context, tokenID string) error {
	ret := _m.Called(ctx, tokenID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockTokenStore_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
func (_e *MockTokenStore_Expecter) RevokeRefreshToken(ctx interface{}, tokenID interface{}) *MockTokenStore_RevokeRefreshToken_Call {
	return &MockTokenStore_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenID)}
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenID string)) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) Return(_a0 error) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenStore_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshTokenFamily provides a mock function with given fields: ctx, tokenFamily
func (_m *MockTokenStore) RevokeRefreshTokenFamily(ctx context.Context, tokenFamily string) error {
	ret := _m.Called(ctx, tokenFamily)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshTokenFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenFamily)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_RevokeRefreshTokenFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshTokenFamily'
type MockTokenStore_RevokeRefreshTokenFamily_Call struct {
	*mock.Call
}

// RevokeRefreshTokenFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenFamily string
func (_e *MockTokenStore_Expecter) RevokeRefreshTokenFamily(ctx interface{}, tokenFamily interface{}) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	return &MockTokenStore_RevokeRefreshTokenFamily_Call{Call: _e.mock.On("RevokeRefreshTokenFamily", ctx, tokenFamily)}
}

func (_c *MockTokenStore_RevokeRefreshTokenFamily_Call) Run(run func(ctx context.Context, tokenFamily string)) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenStore_RevokeRefreshTokenFamily_Call) Return(_a0 error) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_RevokeRefreshTokenFamily_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenStore_RevokeRefreshTokenFamily_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function with given fields: ctx, metadata, ttl
func (_m *MockTokenStore) StoreRefreshToken(ctx context.Context, metadata *RefreshTokenMetadata, ttl time.Duration) error {
	ret := _m.Called(ctx, metadata, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *RefreshTokenMetadata, time.Duration) error); ok {
		r0 = rf(ctx, metadata, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenStore_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockTokenStore_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - metadata *RefreshTokenMetadata
//   - ttl time.Duration
func (_e *MockTokenStore_Expecter) StoreRefreshToken(ctx interface{}, metadata interface{}, ttl interface{}) *MockTokenStore_StoreRefreshToken_Call {
	return &MockTokenStore_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, metadata, ttl)}
}

func (_c *MockTokenStore_StoreRefreshToken_Call) Run(run func(ctx context.Context, metadata *RefreshTokenMetadata, ttl time.Duration)) *MockTokenStore_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*RefreshTokenMetadata), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockTokenStore_StoreRefreshToken_Call) Return(_a0 error) *MockTokenStore_StoreRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenStore_StoreRefreshToken_Call) RunAndReturn(run func(context.Context, *RefreshTokenMetadata, time.Duration) error) *MockTokenStore_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenStore creates a new instance of MockTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenStore {
	mock := &MockTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
