// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const bumpSessionUpdatedAt = `-- name: BumpSessionUpdatedAt :exec
UPDATE chat_sessions
SET updated_at = NOW()
WHERE id = $1
`

// BumpSessionUpdatedAt
//
//	UPDATE chat_sessions
//	SET updated_at = NOW()
//	WHERE id = $1
func (q *Queries) BumpSessionUpdatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, bumpSessionUpdatedAt, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM chat_messages
WHERE session_id = $1
`

// DeleteSessionMessages
//
//	DELETE FROM chat_messages
//	WHERE session_id = $1
func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionMessages, sessionID)
	return err
}

const getLatestSession = `-- name: GetLatestSession :one
SELECT id FROM chat_sessions
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT 1
`

// GetLatestSession
//
//	SELECT id FROM chat_sessions
//	WHERE user_id = $1
//	ORDER BY updated_at DESC
//	LIMIT 1
func (q *Queries) GetLatestSession(ctx context.Context, userID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestSession, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSessionByIDForUser = `-- name: GetSessionByIDForUser :one
SELECT id, user_id, title, created_at, updated_at
FROM chat_sessions
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetSessionByIDForUserParams struct {
	ID     uuid.UUID
	UserID string
}

// GetSessionByIDForUser
//
//	SELECT id, user_id, title, created_at, updated_at
//	FROM chat_sessions
//	WHERE id = $1 AND user_id = $2
//	LIMIT 1
func (q *Queries) GetSessionByIDForUser(ctx context.Context, arg GetSessionByIDForUserParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getSessionByIDForUser, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT role, content FROM chat_messages
WHERE session_id = $1
ORDER BY created_at ASC
`

type GetSessionMessagesRow struct {
	Role    string
	Content string
}

// GetSessionMessages
//
//	SELECT role, content FROM chat_messages
//	WHERE session_id = $1
//	ORDER BY created_at ASC
func (q *Queries) GetSessionMessages(ctx context.Context, sessionID uuid.UUID) ([]GetSessionMessagesRow, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionMessagesRow{}
	for rows.Next() {
		var i GetSessionMessagesRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_id, title, created_at, updated_at
FROM chat_sessions
WHERE user_id = $1
ORDER BY updated_at DESC
`

// GetUserSessions
//
//	SELECT id, user_id, title, created_at, updated_at
//	FROM chat_sessions
//	WHERE user_id = $1
//	ORDER BY updated_at DESC
func (q *Queries) GetUserSessions(ctx context.Context, userID string) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO chat_messages (session_id, role, content)
VALUES ($1, $2, $3)
`

type InsertMessageParams struct {
	SessionID uuid.UUID
	Role      string
	Content   string
}

// InsertMessage
//
//	INSERT INTO chat_messages (session_id, role, content)
//	VALUES ($1, $2, $3)
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage, arg.SessionID, arg.Role, arg.Content)
	return err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO chat_sessions (user_id, title)
VALUES ($1, $2)
RETURNING id
`

type InsertSessionParams struct {
	UserID string
	Title  string
}

// InsertSession
//
//	INSERT INTO chat_sessions (user_id, title)
//	VALUES ($1, $2)
//	RETURNING id
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession, arg.UserID, arg.Title)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
