// Code generated by mockery. DO NOT EDIT.

package server

import (
	context "context"

	domain "github.com/artmexbet/raibecas/services/gateway/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthServiceConnector is an autogenerated mock type for the AuthServiceConnector type
type MockAuthServiceConnector struct {
	mock.Mock
}

type MockAuthServiceConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceConnector) EXPECT() *MockAuthServiceConnector_Expecter {
	return &MockAuthServiceConnector_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function with given fields: ctx, userID, req
func (_m *MockAuthServiceConnector) ChangePassword(ctx context.Context, userID uuid.UUID, req domain.ChangePasswordRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ChangePasswordRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceConnector_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAuthServiceConnector_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req domain.ChangePasswordRequest
func (_e *MockAuthServiceConnector_Expecter) ChangePassword(ctx interface{}, userID interface{}, req interface{}) *MockAuthServiceConnector_ChangePassword_Call {
	return &MockAuthServiceConnector_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, userID, req)}
}

func (_c *MockAuthServiceConnector_ChangePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, req domain.ChangePasswordRequest)) *MockAuthServiceConnector_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.ChangePasswordRequest))
	})
	return _c
}

func (_c *MockAuthServiceConnector_ChangePassword_Call) Return(_a0 error) *MockAuthServiceConnector_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceConnector_ChangePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.ChangePasswordRequest) error) *MockAuthServiceConnector_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockAuthServiceConnector) Login(ctx context.Context, req domain.LoginRequest) (*domain.AuthServiceLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.AuthServiceLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) (*domain.AuthServiceLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LoginRequest) *domain.AuthServiceLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthServiceLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceConnector_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServiceConnector_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.LoginRequest
func (_e *MockAuthServiceConnector_Expecter) Login(ctx interface{}, req interface{}) *MockAuthServiceConnector_Login_Call {
	return &MockAuthServiceConnector_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockAuthServiceConnector_Login_Call) Run(run func(ctx context.Context, req domain.LoginRequest)) *MockAuthServiceConnector_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LoginRequest))
	})
	return _c
}

func (_c *MockAuthServiceConnector_Login_Call) Return(_a0 *domain.AuthServiceLoginResponse, _a1 error) *MockAuthServiceConnector_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceConnector_Login_Call) RunAndReturn(run func(context.Context, domain.LoginRequest) (*domain.AuthServiceLoginResponse, error)) *MockAuthServiceConnector_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, tokenID, accessTokenJTI, userID, token
func (_m *MockAuthServiceConnector) Logout(ctx context.Context, tokenID string, accessTokenJTI string, userID uuid.UUID, token string) error {
	ret := _m.Called(ctx, tokenID, accessTokenJTI, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tokenID, accessTokenJTI, userID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceConnector_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServiceConnector_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenID string
//   - accessTokenJTI string
//   - userID uuid.UUID
//   - token string
func (_e *MockAuthServiceConnector_Expecter) Logout(ctx interface{}, tokenID interface{}, accessTokenJTI interface{}, userID interface{}, token interface{}) *MockAuthServiceConnector_Logout_Call {
	return &MockAuthServiceConnector_Logout_Call{Call: _e.mock.On("Logout", ctx, tokenID, accessTokenJTI, userID, token)}
}

func (_c *MockAuthServiceConnector_Logout_Call) Run(run func(ctx context.Context, tokenID string, accessTokenJTI string, userID uuid.UUID, token string)) *MockAuthServiceConnector_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *MockAuthServiceConnector_Logout_Call) Return(_a0 error) *MockAuthServiceConnector_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceConnector_Logout_Call) RunAndReturn(run func(context.Context, string, string, uuid.UUID, string) error) *MockAuthServiceConnector_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, userID, token
func (_m *MockAuthServiceConnector) LogoutAll(ctx context.Context, userID uuid.UUID, token string) error {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceConnector_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAuthServiceConnector_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - token string
func (_e *MockAuthServiceConnector_Expecter) LogoutAll(ctx interface{}, userID interface{}, token interface{}) *MockAuthServiceConnector_LogoutAll_Call {
	return &MockAuthServiceConnector_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, userID, token)}
}

func (_c *MockAuthServiceConnector_LogoutAll_Call) Run(run func(ctx context.Context, userID uuid.UUID, token string)) *MockAuthServiceConnector_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockAuthServiceConnector_LogoutAll_Call) Return(_a0 error) *MockAuthServiceConnector_LogoutAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceConnector_LogoutAll_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockAuthServiceConnector_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: ctx, req
func (_m *MockAuthServiceConnector) RefreshToken(ctx context.Context, req domain.AuthServiceRefreshRequest) (*domain.AuthServiceLoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *domain.AuthServiceLoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthServiceRefreshRequest) (*domain.AuthServiceLoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthServiceRefreshRequest) *domain.AuthServiceLoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthServiceLoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthServiceRefreshRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceConnector_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockAuthServiceConnector_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.AuthServiceRefreshRequest
func (_e *MockAuthServiceConnector_Expecter) RefreshToken(ctx interface{}, req interface{}) *MockAuthServiceConnector_RefreshToken_Call {
	return &MockAuthServiceConnector_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, req)}
}

func (_c *MockAuthServiceConnector_RefreshToken_Call) Run(run func(ctx context.Context, req domain.AuthServiceRefreshRequest)) *MockAuthServiceConnector_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.AuthServiceRefreshRequest))
	})
	return _c
}

func (_c *MockAuthServiceConnector_RefreshToken_Call) Return(_a0 *domain.AuthServiceLoginResponse, _a1 error) *MockAuthServiceConnector_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceConnector_RefreshToken_Call) RunAndReturn(run func(context.Context, domain.AuthServiceRefreshRequest) (*domain.AuthServiceLoginResponse, error)) *MockAuthServiceConnector_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: ctx, token, fingerprint
func (_m *MockAuthServiceConnector) ValidateToken(ctx context.Context, token string, fingerprint string) (*domain.ValidateTokenResponse, error) {
	ret := _m.Called(ctx, token, fingerprint)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *domain.ValidateTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.ValidateTokenResponse, error)); ok {
		return rf(ctx, token, fingerprint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.ValidateTokenResponse); ok {
		r0 = rf(ctx, token, fingerprint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ValidateTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, fingerprint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceConnector_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockAuthServiceConnector_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - fingerprint string
func (_e *MockAuthServiceConnector_Expecter) ValidateToken(ctx interface{}, token interface{}, fingerprint interface{}) *MockAuthServiceConnector_ValidateToken_Call {
	return &MockAuthServiceConnector_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token, fingerprint)}
}

func (_c *MockAuthServiceConnector_ValidateToken_Call) Run(run func(ctx context.Context, token string, fingerprint string)) *MockAuthServiceConnector_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthServiceConnector_ValidateToken_Call) Return(_a0 *domain.ValidateTokenResponse, _a1 error) *MockAuthServiceConnector_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceConnector_ValidateToken_Call) RunAndReturn(run func(context.Context, string, string) (*domain.ValidateTokenResponse, error)) *MockAuthServiceConnector_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTokenWS provides a mock function with given fields: ctx, token
func (_m *MockAuthServiceConnector) ValidateTokenWS(ctx context.Context, token string) (*domain.ValidateTokenResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTokenWS")
	}

	var r0 *domain.ValidateTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ValidateTokenResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ValidateTokenResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ValidateTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceConnector_ValidateTokenWS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTokenWS'
type MockAuthServiceConnector_ValidateTokenWS_Call struct {
	*mock.Call
}

// ValidateTokenWS is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthServiceConnector_Expecter) ValidateTokenWS(ctx interface{}, token interface{}) *MockAuthServiceConnector_ValidateTokenWS_Call {
	return &MockAuthServiceConnector_ValidateTokenWS_Call{Call: _e.mock.On("ValidateTokenWS", ctx, token)}
}

func (_c *MockAuthServiceConnector_ValidateTokenWS_Call) Run(run func(ctx context.Context, token string)) *MockAuthServiceConnector_ValidateTokenWS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceConnector_ValidateTokenWS_Call) Return(_a0 *domain.ValidateTokenResponse, _a1 error) *MockAuthServiceConnector_ValidateTokenWS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceConnector_ValidateTokenWS_Call) RunAndReturn(run func(context.Context, string) (*domain.ValidateTokenResponse, error)) *MockAuthServiceConnector_ValidateTokenWS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceConnector creates a new instance of MockAuthServiceConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceConnector {
	mock := &MockAuthServiceConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
