// Code generated by mockery. DO NOT EDIT.

package server

import (
	context "context"

	domain "github.com/artmexbet/raibecas/services/gateway/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserServiceConnector is an autogenerated mock type for the UserServiceConnector type
type MockUserServiceConnector struct {
	mock.Mock
}

type MockUserServiceConnector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServiceConnector) EXPECT() *MockUserServiceConnector_Expecter {
	return &MockUserServiceConnector_Expecter{mock: &_m.Mock}
}

// ApproveRegistrationRequest provides a mock function with given fields: ctx, requestID, approverID, role
func (_m *MockUserServiceConnector) ApproveRegistrationRequest(ctx context.Context, requestID uuid.UUID, approverID uuid.UUID, role string) (*domain.ApproveRegistrationRequestResponse, error) {
	ret := _m.Called(ctx, requestID, approverID, role)

	if len(ret) == 0 {
		panic("no return value specified for ApproveRegistrationRequest")
	}

	var r0 *domain.ApproveRegistrationRequestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.ApproveRegistrationRequestResponse, error)); ok {
		return rf(ctx, requestID, approverID, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *domain.ApproveRegistrationRequestResponse); ok {
		r0 = rf(ctx, requestID, approverID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApproveRegistrationRequestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, requestID, approverID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_ApproveRegistrationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveRegistrationRequest'
type MockUserServiceConnector_ApproveRegistrationRequest_Call struct {
	*mock.Call
}

// ApproveRegistrationRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - approverID uuid.UUID
//   - role string
func (_e *MockUserServiceConnector_Expecter) ApproveRegistrationRequest(ctx interface{}, requestID interface{}, approverID interface{}, role interface{}) *MockUserServiceConnector_ApproveRegistrationRequest_Call {
	return &MockUserServiceConnector_ApproveRegistrationRequest_Call{Call: _e.mock.On("ApproveRegistrationRequest", ctx, requestID, approverID, role)}
}

func (_c *MockUserServiceConnector_ApproveRegistrationRequest_Call) Run(run func(ctx context.Context, requestID uuid.UUID, approverID uuid.UUID, role string)) *MockUserServiceConnector_ApproveRegistrationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockUserServiceConnector_ApproveRegistrationRequest_Call) Return(_a0 *domain.ApproveRegistrationRequestResponse, _a1 error) *MockUserServiceConnector_ApproveRegistrationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_ApproveRegistrationRequest_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.ApproveRegistrationRequestResponse, error)) *MockUserServiceConnector_ApproveRegistrationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRegistrationRequest provides a mock function with given fields: ctx, req
func (_m *MockUserServiceConnector) CreateRegistrationRequest(ctx context.Context, req domain.CreateRegistrationRequestRequest) (*domain.CreateRegistrationRequestResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRegistrationRequest")
	}

	var r0 *domain.CreateRegistrationRequestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateRegistrationRequestRequest) (*domain.CreateRegistrationRequestResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateRegistrationRequestRequest) *domain.CreateRegistrationRequestResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateRegistrationRequestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateRegistrationRequestRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_CreateRegistrationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRegistrationRequest'
type MockUserServiceConnector_CreateRegistrationRequest_Call struct {
	*mock.Call
}

// CreateRegistrationRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateRegistrationRequestRequest
func (_e *MockUserServiceConnector_Expecter) CreateRegistrationRequest(ctx interface{}, req interface{}) *MockUserServiceConnector_CreateRegistrationRequest_Call {
	return &MockUserServiceConnector_CreateRegistrationRequest_Call{Call: _e.mock.On("CreateRegistrationRequest", ctx, req)}
}

func (_c *MockUserServiceConnector_CreateRegistrationRequest_Call) Run(run func(ctx context.Context, req domain.CreateRegistrationRequestRequest)) *MockUserServiceConnector_CreateRegistrationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreateRegistrationRequestRequest))
	})
	return _c
}

func (_c *MockUserServiceConnector_CreateRegistrationRequest_Call) Return(_a0 *domain.CreateRegistrationRequestResponse, _a1 error) *MockUserServiceConnector_CreateRegistrationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_CreateRegistrationRequest_Call) RunAndReturn(run func(context.Context, domain.CreateRegistrationRequestRequest) (*domain.CreateRegistrationRequestResponse, error)) *MockUserServiceConnector_CreateRegistrationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, id
func (_m *MockUserServiceConnector) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServiceConnector_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserServiceConnector_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserServiceConnector_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserServiceConnector_DeleteUser_Call {
	return &MockUserServiceConnector_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserServiceConnector_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserServiceConnector_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServiceConnector_DeleteUser_Call) Return(_a0 error) *MockUserServiceConnector_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServiceConnector_DeleteUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockUserServiceConnector_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, id
func (_m *MockUserServiceConnector) GetUser(ctx context.Context, id uuid.UUID) (*domain.GetUserResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.GetUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.GetUserResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.GetUserResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.GetUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserServiceConnector_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserServiceConnector_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserServiceConnector_GetUser_Call {
	return &MockUserServiceConnector_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserServiceConnector_GetUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserServiceConnector_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServiceConnector_GetUser_Call) Return(_a0 *domain.GetUserResponse, _a1 error) *MockUserServiceConnector_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_GetUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.GetUserResponse, error)) *MockUserServiceConnector_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListRegistrationRequests provides a mock function with given fields: ctx, query
func (_m *MockUserServiceConnector) ListRegistrationRequests(ctx context.Context, query domain.ListRegistrationRequestsQuery) (*domain.ListRegistrationRequestsResponse, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListRegistrationRequests")
	}

	var r0 *domain.ListRegistrationRequestsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListRegistrationRequestsQuery) (*domain.ListRegistrationRequestsResponse, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListRegistrationRequestsQuery) *domain.ListRegistrationRequestsResponse); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListRegistrationRequestsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListRegistrationRequestsQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_ListRegistrationRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRegistrationRequests'
type MockUserServiceConnector_ListRegistrationRequests_Call struct {
	*mock.Call
}

// ListRegistrationRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.ListRegistrationRequestsQuery
func (_e *MockUserServiceConnector_Expecter) ListRegistrationRequests(ctx interface{}, query interface{}) *MockUserServiceConnector_ListRegistrationRequests_Call {
	return &MockUserServiceConnector_ListRegistrationRequests_Call{Call: _e.mock.On("ListRegistrationRequests", ctx, query)}
}

func (_c *MockUserServiceConnector_ListRegistrationRequests_Call) Run(run func(ctx context.Context, query domain.ListRegistrationRequestsQuery)) *MockUserServiceConnector_ListRegistrationRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListRegistrationRequestsQuery))
	})
	return _c
}

func (_c *MockUserServiceConnector_ListRegistrationRequests_Call) Return(_a0 *domain.ListRegistrationRequestsResponse, _a1 error) *MockUserServiceConnector_ListRegistrationRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_ListRegistrationRequests_Call) RunAndReturn(run func(context.Context, domain.ListRegistrationRequestsQuery) (*domain.ListRegistrationRequestsResponse, error)) *MockUserServiceConnector_ListRegistrationRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, query
func (_m *MockUserServiceConnector) ListUsers(ctx context.Context, query domain.ListUsersQuery) (*domain.ListUsersResponse, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *domain.ListUsersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListUsersQuery) (*domain.ListUsersResponse, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListUsersQuery) *domain.ListUsersResponse); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListUsersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListUsersQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserServiceConnector_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.ListUsersQuery
func (_e *MockUserServiceConnector_Expecter) ListUsers(ctx interface{}, query interface{}) *MockUserServiceConnector_ListUsers_Call {
	return &MockUserServiceConnector_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, query)}
}

func (_c *MockUserServiceConnector_ListUsers_Call) Run(run func(ctx context.Context, query domain.ListUsersQuery)) *MockUserServiceConnector_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListUsersQuery))
	})
	return _c
}

func (_c *MockUserServiceConnector_ListUsers_Call) Return(_a0 *domain.ListUsersResponse, _a1 error) *MockUserServiceConnector_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_ListUsers_Call) RunAndReturn(run func(context.Context, domain.ListUsersQuery) (*domain.ListUsersResponse, error)) *MockUserServiceConnector_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RejectRegistrationRequest provides a mock function with given fields: ctx, requestID, approverID, reason
func (_m *MockUserServiceConnector) RejectRegistrationRequest(ctx context.Context, requestID uuid.UUID, approverID uuid.UUID, reason string) (*domain.RejectRegistrationRequestResponse, error) {
	ret := _m.Called(ctx, requestID, approverID, reason)

	if len(ret) == 0 {
		panic("no return value specified for RejectRegistrationRequest")
	}

	var r0 *domain.RejectRegistrationRequestResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.RejectRegistrationRequestResponse, error)); ok {
		return rf(ctx, requestID, approverID, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *domain.RejectRegistrationRequestResponse); ok {
		r0 = rf(ctx, requestID, approverID, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RejectRegistrationRequestResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = rf(ctx, requestID, approverID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_RejectRegistrationRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectRegistrationRequest'
type MockUserServiceConnector_RejectRegistrationRequest_Call struct {
	*mock.Call
}

// RejectRegistrationRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID uuid.UUID
//   - approverID uuid.UUID
//   - reason string
func (_e *MockUserServiceConnector_Expecter) RejectRegistrationRequest(ctx interface{}, requestID interface{}, approverID interface{}, reason interface{}) *MockUserServiceConnector_RejectRegistrationRequest_Call {
	return &MockUserServiceConnector_RejectRegistrationRequest_Call{Call: _e.mock.On("RejectRegistrationRequest", ctx, requestID, approverID, reason)}
}

func (_c *MockUserServiceConnector_RejectRegistrationRequest_Call) Run(run func(ctx context.Context, requestID uuid.UUID, approverID uuid.UUID, reason string)) *MockUserServiceConnector_RejectRegistrationRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockUserServiceConnector_RejectRegistrationRequest_Call) Return(_a0 *domain.RejectRegistrationRequestResponse, _a1 error) *MockUserServiceConnector_RejectRegistrationRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_RejectRegistrationRequest_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, string) (*domain.RejectRegistrationRequestResponse, error)) *MockUserServiceConnector_RejectRegistrationRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, id, req
func (_m *MockUserServiceConnector) UpdateUser(ctx context.Context, id uuid.UUID, req domain.UpdateUserRequest) (*domain.UpdateUserResponse, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *domain.UpdateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UpdateUserRequest) (*domain.UpdateUserResponse, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.UpdateUserRequest) *domain.UpdateUserResponse); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UpdateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.UpdateUserRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServiceConnector_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserServiceConnector_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req domain.UpdateUserRequest
func (_e *MockUserServiceConnector_Expecter) UpdateUser(ctx interface{}, id interface{}, req interface{}) *MockUserServiceConnector_UpdateUser_Call {
	return &MockUserServiceConnector_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, req)}
}

func (_c *MockUserServiceConnector_UpdateUser_Call) Run(run func(ctx context.Context, id uuid.UUID, req domain.UpdateUserRequest)) *MockUserServiceConnector_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.UpdateUserRequest))
	})
	return _c
}

func (_c *MockUserServiceConnector_UpdateUser_Call) Return(_a0 *domain.UpdateUserResponse, _a1 error) *MockUserServiceConnector_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServiceConnector_UpdateUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.UpdateUserRequest) (*domain.UpdateUserResponse, error)) *MockUserServiceConnector_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServiceConnector creates a new instance of MockUserServiceConnector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServiceConnector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServiceConnector {
	mock := &MockUserServiceConnector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
