// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDocumentAuthor = `-- name: AddDocumentAuthor :exec
INSERT INTO document_authors (document_id, author_id, type_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddDocumentAuthorParams struct {
	DocumentID uuid.UUID
	AuthorID   uuid.UUID
	TypeID     int32
}

// AddDocumentAuthor
//
//	INSERT INTO document_authors (document_id, author_id, type_id)
//	VALUES ($1, $2, $3)
//	ON CONFLICT DO NOTHING
func (q *Queries) AddDocumentAuthor(ctx context.Context, arg AddDocumentAuthorParams) error {
	_, err := q.db.Exec(ctx, addDocumentAuthor, arg.DocumentID, arg.AuthorID, arg.TypeID)
	return err
}

const addDocumentTag = `-- name: AddDocumentTag :exec
INSERT INTO document_tags (document_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDocumentTagParams struct {
	DocumentID uuid.UUID
	TagID      int32
}

// AddDocumentTag
//
//	INSERT INTO document_tags (document_id, tag_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) AddDocumentTag(ctx context.Context, arg AddDocumentTagParams) error {
	_, err := q.db.Exec(ctx, addDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const clearDocumentAuthors = `-- name: ClearDocumentAuthors :exec
DELETE FROM document_authors
WHERE document_id = $1
`

// ClearDocumentAuthors
//
//	DELETE FROM document_authors
//	WHERE document_id = $1
func (q *Queries) ClearDocumentAuthors(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDocumentAuthors, documentID)
	return err
}

const clearDocumentTags = `-- name: ClearDocumentTags :exec
DELETE FROM document_tags
WHERE document_id = $1
`

// ClearDocumentTags
//
//	DELETE FROM document_tags
//	WHERE document_id = $1
func (q *Queries) ClearDocumentTags(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDocumentTags, documentID)
	return err
}

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents
WHERE (
    CASE
        WHEN $1::uuid IS NOT NULL THEN EXISTS (
            SELECT 1
            FROM document_authors da
            WHERE da.document_id = documents.id
              AND da.author_id = $1::uuid
        )
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $2::int IS NOT NULL THEN category_id = $2::int
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $3::int IS NOT NULL THEN document_type_id = $3::int
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $4::int IS NOT NULL THEN EXISTS (
            SELECT 1
            FROM document_tags dt
            WHERE dt.document_id = documents.id
              AND dt.tag_id = $4::int
        )
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $5::text IS NOT NULL AND $5::text != ''
        THEN (
            to_tsvector('russian', title || ' ' || COALESCE(description, '') || ' ' || COALESCE((SELECT name FROM document_types WHERE id = documents.document_type_id), '')) @@ plainto_tsquery('russian', $5::text)
            OR EXISTS (
                SELECT 1
                FROM document_authors da
                JOIN authors a ON a.id = da.author_id
                JOIN authorship_types at ON at.id = da.type_id
                WHERE da.document_id = documents.id
                  AND (
                      a.name ILIKE '%' || $5::text || '%'
                      OR at.title ILIKE '%' || $5::text || '%'
                  )
            )
            OR EXISTS (
                SELECT 1
                FROM document_tags dt
                JOIN tags t ON t.id = dt.tag_id
                WHERE dt.document_id = documents.id
                  AND t.title ILIKE '%' || $5::text || '%'
            )
        )
        ELSE TRUE
    END
)
`

type CountDocumentsParams struct {
	AuthorID       *uuid.UUID
	CategoryID     *int32
	DocumentTypeID *int32
	TagID          *int32
	Search         *string
}

// CountDocuments
//
//	SELECT COUNT(*) FROM documents
//	WHERE (
//	    CASE
//	        WHEN $1::uuid IS NOT NULL THEN EXISTS (
//	            SELECT 1
//	            FROM document_authors da
//	            WHERE da.document_id = documents.id
//	              AND da.author_id = $1::uuid
//	        )
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $2::int IS NOT NULL THEN category_id = $2::int
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $3::int IS NOT NULL THEN document_type_id = $3::int
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $4::int IS NOT NULL THEN EXISTS (
//	            SELECT 1
//	            FROM document_tags dt
//	            WHERE dt.document_id = documents.id
//	              AND dt.tag_id = $4::int
//	        )
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $5::text IS NOT NULL AND $5::text != ''
//	        THEN (
//	            to_tsvector('russian', title || ' ' || COALESCE(description, '') || ' ' || COALESCE((SELECT name FROM document_types WHERE id = documents.document_type_id), '')) @@ plainto_tsquery('russian', $5::text)
//	            OR EXISTS (
//	                SELECT 1
//	                FROM document_authors da
//	                JOIN authors a ON a.id = da.author_id
//	                JOIN authorship_types at ON at.id = da.type_id
//	                WHERE da.document_id = documents.id
//	                  AND (
//	                      a.name ILIKE '%' || $5::text || '%'
//	                      OR at.title ILIKE '%' || $5::text || '%'
//	                  )
//	            )
//	            OR EXISTS (
//	                SELECT 1
//	                FROM document_tags dt
//	                JOIN tags t ON t.id = dt.tag_id
//	                WHERE dt.document_id = documents.id
//	                  AND t.title ILIKE '%' || $5::text || '%'
//	            )
//	        )
//	        ELSE TRUE
//	    END
//	)
func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments,
		arg.AuthorID,
		arg.CategoryID,
		arg.DocumentTypeID,
		arg.TagID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (id, name, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, bio, created_at, updated_at
`

type CreateAuthorParams struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// CreateAuthor
//
//	INSERT INTO authors (id, name, created_at, updated_at)
//	VALUES ($1, $2, $3, $4)
//	RETURNING id, name, bio, created_at, updated_at
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (title, created_at)
VALUES ($1, $2)
RETURNING id, title, description, created_at
`

type CreateCategoryParams struct {
	Title     string
	CreatedAt time.Time
}

// CreateCategory
//
//	INSERT INTO categories (title, created_at)
//	VALUES ($1, $2)
//	RETURNING id, title, description, created_at
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Title, arg.CreatedAt)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    title,
    description,
    category_id,
    publication_date,
    content_path,
    current_version,
    document_type_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at, cover_path, document_type_id
`

type CreateDocumentParams struct {
	Title           string
	Description     *string
	CategoryID      *int32
	PublicationDate pgtype.Date
	ContentPath     string
	CurrentVersion  int32
	DocumentTypeID  int32
}

// CreateDocument
//
//	INSERT INTO documents (
//	    title,
//	    description,
//	    category_id,
//	    publication_date,
//	    content_path,
//	    current_version,
//	    document_type_id
//	) VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, title, description, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at, cover_path, document_type_id
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.PublicationDate,
		arg.ContentPath,
		arg.CurrentVersion,
		arg.DocumentTypeID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.PublicationDate,
		&i.ContentPath,
		&i.CurrentVersion,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverPath,
		&i.DocumentTypeID,
	)
	return i, err
}

const createDocumentType = `-- name: CreateDocumentType :one
INSERT INTO document_types (name)
VALUES ($1)
RETURNING id, name, created_at
`

// CreateDocumentType
//
//	INSERT INTO document_types (name)
//	VALUES ($1)
//	RETURNING id, name, created_at
func (q *Queries) CreateDocumentType(ctx context.Context, name string) (DocumentType, error) {
	row := q.db.QueryRow(ctx, createDocumentType, name)
	var i DocumentType
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
    document_id,
    version,
    content_path,
    changes,
    created_by
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, version, content_path, changes, created_by, created_at
`

type CreateDocumentVersionParams struct {
	DocumentID  uuid.UUID
	Version     int32
	ContentPath string
	Changes     *string
	CreatedBy   *uuid.UUID
}

// CreateDocumentVersion
//
//	INSERT INTO document_versions (
//	    document_id,
//	    version,
//	    content_path,
//	    changes,
//	    created_by
//	) VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, document_id, version, content_path, changes, created_by, created_at
func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.ContentPath,
		arg.Changes,
		arg.CreatedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ContentPath,
		&i.Changes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (title, created_at)
VALUES ($1, $2)
RETURNING id, title, created_at
`

type CreateTagParams struct {
	Title     string
	CreatedAt time.Time
}

// CreateTag
//
//	INSERT INTO tags (title, created_at)
//	VALUES ($1, $2)
//	RETURNING id, title, created_at
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Title, arg.CreatedAt)
	var i Tag
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

// DeleteDocument
//
//	DELETE FROM documents
//	WHERE id = $1
func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, bio, created_at, updated_at FROM authors
WHERE id = $1
`

// GetAuthorByID
//
//	SELECT id, name, bio, created_at, updated_at FROM authors
//	WHERE id = $1
func (q *Queries) GetAuthorByID(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, title, description, created_at FROM categories
WHERE id = $1
`

// GetCategoryByID
//
//	SELECT id, title, description, created_at FROM categories
//	WHERE id = $1
func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentAuthors = `-- name: GetDocumentAuthors :many
SELECT
    da.document_id,
    a.id AS author_id,
    a.name AS author_name,
    a.bio AS author_bio,
    a.created_at AS author_created_at,
    a.updated_at AS author_updated_at,
    at.id AS authorship_type_id,
    at.title AS authorship_type_title,
    at.created_at AS authorship_type_created_at
FROM document_authors da
INNER JOIN authors a ON a.id = da.author_id
INNER JOIN authorship_types at ON at.id = da.type_id
WHERE da.document_id = $1
ORDER BY
    CASE at.title
        WHEN 'автор' THEN 0
        WHEN 'редактор' THEN 1
        WHEN 'рецензент' THEN 2
        ELSE 10
    END,
    a.name
`

type GetDocumentAuthorsRow struct {
	DocumentID              uuid.UUID
	AuthorID                uuid.UUID
	AuthorName              string
	AuthorBio               *string
	AuthorCreatedAt         time.Time
	AuthorUpdatedAt         time.Time
	AuthorshipTypeID        int32
	AuthorshipTypeTitle     string
	AuthorshipTypeCreatedAt time.Time
}

// GetDocumentAuthors
//
//	SELECT
//	    da.document_id,
//	    a.id AS author_id,
//	    a.name AS author_name,
//	    a.bio AS author_bio,
//	    a.created_at AS author_created_at,
//	    a.updated_at AS author_updated_at,
//	    at.id AS authorship_type_id,
//	    at.title AS authorship_type_title,
//	    at.created_at AS authorship_type_created_at
//	FROM document_authors da
//	INNER JOIN authors a ON a.id = da.author_id
//	INNER JOIN authorship_types at ON at.id = da.type_id
//	WHERE da.document_id = $1
//	ORDER BY
//	    CASE at.title
//	        WHEN 'автор' THEN 0
//	        WHEN 'редактор' THEN 1
//	        WHEN 'рецензент' THEN 2
//	        ELSE 10
//	    END,
//	    a.name
func (q *Queries) GetDocumentAuthors(ctx context.Context, documentID uuid.UUID) ([]GetDocumentAuthorsRow, error) {
	rows, err := q.db.Query(ctx, getDocumentAuthors, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentAuthorsRow{}
	for rows.Next() {
		var i GetDocumentAuthorsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorBio,
			&i.AuthorCreatedAt,
			&i.AuthorUpdatedAt,
			&i.AuthorshipTypeID,
			&i.AuthorshipTypeTitle,
			&i.AuthorshipTypeCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT
    documents.id, documents.title, documents.description, documents.category_id, documents.publication_date, documents.content_path, documents.current_version, documents.indexed, documents.created_at, documents.updated_at, documents.cover_path, documents.document_type_id,
    categories.id, categories.title, categories.description, categories.created_at,
    document_types.id, document_types.name, document_types.created_at
FROM documents
LEFT JOIN categories ON documents.category_id = categories.id
LEFT JOIN document_types ON documents.document_type_id = document_types.id
WHERE documents.id = $1
`

type GetDocumentByIDRow struct {
	ID              uuid.UUID
	Title           string
	Description     *string
	CategoryID      *int32
	PublicationDate pgtype.Date
	ContentPath     string
	CurrentVersion  int32
	Indexed         bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CoverPath       *string
	DocumentTypeID  int32
	Category        Category
	DocumentType    DocumentType
}

// GetDocumentByID
//
//	SELECT
//	    documents.id, documents.title, documents.description, documents.category_id, documents.publication_date, documents.content_path, documents.current_version, documents.indexed, documents.created_at, documents.updated_at, documents.cover_path, documents.document_type_id,
//	    categories.id, categories.title, categories.description, categories.created_at,
//	    document_types.id, document_types.name, document_types.created_at
//	FROM documents
//	LEFT JOIN categories ON documents.category_id = categories.id
//	LEFT JOIN document_types ON documents.document_type_id = document_types.id
//	WHERE documents.id = $1
func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.PublicationDate,
		&i.ContentPath,
		&i.CurrentVersion,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverPath,
		&i.DocumentTypeID,
		&i.Category.ID,
		&i.Category.Title,
		&i.Category.Description,
		&i.Category.CreatedAt,
		&i.DocumentType.ID,
		&i.DocumentType.Name,
		&i.DocumentType.CreatedAt,
	)
	return i, err
}

const getDocumentTags = `-- name: GetDocumentTags :many
SELECT t.id, t.title, t.created_at FROM tags t
INNER JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = $1
ORDER BY t.title
`

// GetDocumentTags
//
//	SELECT t.id, t.title, t.created_at FROM tags t
//	INNER JOIN document_tags dt ON dt.tag_id = t.id
//	WHERE dt.document_id = $1
//	ORDER BY t.title
func (q *Queries) GetDocumentTags(ctx context.Context, documentID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentTypeByID = `-- name: GetDocumentTypeByID :one
SELECT id, name, created_at FROM document_types
WHERE id = $1
`

// GetDocumentTypeByID
//
//	SELECT id, name, created_at FROM document_types
//	WHERE id = $1
func (q *Queries) GetDocumentTypeByID(ctx context.Context, id int32) (DocumentType, error) {
	row := q.db.QueryRow(ctx, getDocumentTypeByID, id)
	var i DocumentType
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
WHERE document_id = $1 AND version = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID
	Version    int32
}

// GetDocumentVersion
//
//	SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
//	WHERE document_id = $1 AND version = $2
func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ContentPath,
		&i.Changes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, title, created_at FROM tags
WHERE id = $1
`

// GetTagByID
//
//	SELECT id, title, created_at FROM tags
//	WHERE id = $1
func (q *Queries) GetTagByID(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, created_at, updated_at FROM authors
ORDER BY name
`

// ListAuthors
//
//	SELECT id, name, bio, created_at, updated_at FROM authors
//	ORDER BY name
func (q *Queries) ListAuthors(ctx context.Context) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorshipTypes = `-- name: ListAuthorshipTypes :many
SELECT id, title, created_at FROM authorship_types
ORDER BY id
`

// ListAuthorshipTypes
//
//	SELECT id, title, created_at FROM authorship_types
//	ORDER BY id
func (q *Queries) ListAuthorshipTypes(ctx context.Context) ([]AuthorshipType, error) {
	rows, err := q.db.Query(ctx, listAuthorshipTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthorshipType{}
	for rows.Next() {
		var i AuthorshipType
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, title, description, created_at FROM categories
ORDER BY title
`

// ListCategories
//
//	SELECT id, title, description, created_at FROM categories
//	ORDER BY title
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTypes = `-- name: ListDocumentTypes :many
SELECT id, name, created_at FROM document_types
ORDER BY name
`

// ListDocumentTypes
//
//	SELECT id, name, created_at FROM document_types
//	ORDER BY name
func (q *Queries) ListDocumentTypes(ctx context.Context) ([]DocumentType, error) {
	rows, err := q.db.Query(ctx, listDocumentTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentType{}
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
WHERE document_id = $1
ORDER BY version DESC
`

// ListDocumentVersions
//
//	SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
//	WHERE document_id = $1
//	ORDER BY version DESC
func (q *Queries) ListDocumentVersions(ctx context.Context, documentID uuid.UUID) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.ContentPath,
			&i.Changes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT
    d.id, d.title, d.description, d.category_id, d.publication_date, d.content_path, d.current_version, d.indexed, d.created_at, d.updated_at, d.cover_path, d.document_type_id,
    c.id, c.title, c.description, c.created_at,
    dt.id, dt.name, dt.created_at
FROM documents d
LEFT JOIN categories c ON d.category_id = c.id
LEFT JOIN document_types dt ON d.document_type_id = dt.id
WHERE (
    CASE
        WHEN $3::uuid IS NOT NULL THEN EXISTS (
            SELECT 1
            FROM document_authors da
            WHERE da.document_id = d.id
              AND da.author_id = $3::uuid
        )
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $4::int IS NOT NULL THEN d.category_id = $4::int
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $5::int IS NOT NULL THEN d.document_type_id = $5::int
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $6::int IS NOT NULL THEN EXISTS (
            SELECT 1
            FROM document_tags dtt
            WHERE dtt.document_id = d.id
              AND dtt.tag_id = $6::int
        )
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $7::text IS NOT NULL AND $7::text != ''
        THEN (
            to_tsvector('russian', d.title || ' ' || COALESCE(d.description, '') || ' ' || COALESCE(dt.name, '')) @@ plainto_tsquery('russian', $7::text)
            OR EXISTS (
                SELECT 1
                FROM document_authors da
                JOIN authors sa ON sa.id = da.author_id
                JOIN authorship_types sat ON sat.id = da.type_id
                WHERE da.document_id = d.id
                  AND (
                      sa.name ILIKE '%' || $7::text || '%'
                      OR sat.title ILIKE '%' || $7::text || '%'
                  )
            )
            OR EXISTS (
                SELECT 1
                FROM document_tags dtt
                JOIN tags tt ON tt.id = dtt.tag_id
                WHERE dtt.document_id = d.id
                  AND tt.title ILIKE '%' || $7::text || '%'
            )
        )
        ELSE TRUE
    END
)
ORDER BY d.created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit          int32
	Offset         int32
	AuthorID       *uuid.UUID
	CategoryID     *int32
	DocumentTypeID *int32
	TagID          *int32
	Search         *string
}

type ListDocumentsRow struct {
	ID              uuid.UUID
	Title           string
	Description     *string
	CategoryID      *int32
	PublicationDate pgtype.Date
	ContentPath     string
	CurrentVersion  int32
	Indexed         bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CoverPath       *string
	DocumentTypeID  int32
	Category        Category
	DocumentType    DocumentType
}

// ListDocuments
//
//	SELECT
//	    d.id, d.title, d.description, d.category_id, d.publication_date, d.content_path, d.current_version, d.indexed, d.created_at, d.updated_at, d.cover_path, d.document_type_id,
//	    c.id, c.title, c.description, c.created_at,
//	    dt.id, dt.name, dt.created_at
//	FROM documents d
//	LEFT JOIN categories c ON d.category_id = c.id
//	LEFT JOIN document_types dt ON d.document_type_id = dt.id
//	WHERE (
//	    CASE
//	        WHEN $3::uuid IS NOT NULL THEN EXISTS (
//	            SELECT 1
//	            FROM document_authors da
//	            WHERE da.document_id = d.id
//	              AND da.author_id = $3::uuid
//	        )
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $4::int IS NOT NULL THEN d.category_id = $4::int
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $5::int IS NOT NULL THEN d.document_type_id = $5::int
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $6::int IS NOT NULL THEN EXISTS (
//	            SELECT 1
//	            FROM document_tags dtt
//	            WHERE dtt.document_id = d.id
//	              AND dtt.tag_id = $6::int
//	        )
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $7::text IS NOT NULL AND $7::text != ''
//	        THEN (
//	            to_tsvector('russian', d.title || ' ' || COALESCE(d.description, '') || ' ' || COALESCE(dt.name, '')) @@ plainto_tsquery('russian', $7::text)
//	            OR EXISTS (
//	                SELECT 1
//	                FROM document_authors da
//	                JOIN authors sa ON sa.id = da.author_id
//	                JOIN authorship_types sat ON sat.id = da.type_id
//	                WHERE da.document_id = d.id
//	                  AND (
//	                      sa.name ILIKE '%' || $7::text || '%'
//	                      OR sat.title ILIKE '%' || $7::text || '%'
//	                  )
//	            )
//	            OR EXISTS (
//	                SELECT 1
//	                FROM document_tags dtt
//	                JOIN tags tt ON tt.id = dtt.tag_id
//	                WHERE dtt.document_id = d.id
//	                  AND tt.title ILIKE '%' || $7::text || '%'
//	            )
//	        )
//	        ELSE TRUE
//	    END
//	)
//	ORDER BY d.created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.Limit,
		arg.Offset,
		arg.AuthorID,
		arg.CategoryID,
		arg.DocumentTypeID,
		arg.TagID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CategoryID,
			&i.PublicationDate,
			&i.ContentPath,
			&i.CurrentVersion,
			&i.Indexed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CoverPath,
			&i.DocumentTypeID,
			&i.Category.ID,
			&i.Category.Title,
			&i.Category.Description,
			&i.Category.CreatedAt,
			&i.DocumentType.ID,
			&i.DocumentType.Name,
			&i.DocumentType.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, title, created_at FROM tags
ORDER BY title
`

// ListTags
//
//	SELECT id, title, created_at FROM tags
//	ORDER BY title
func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentTag = `-- name: RemoveDocumentTag :exec
DELETE FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

type RemoveDocumentTagParams struct {
	DocumentID uuid.UUID
	TagID      int32
}

// RemoveDocumentTag
//
//	DELETE FROM document_tags
//	WHERE document_id = $1 AND tag_id = $2
func (q *Queries) RemoveDocumentTag(ctx context.Context, arg RemoveDocumentTagParams) error {
	_, err := q.db.Exec(ctx, removeDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    category_id = COALESCE($4, category_id),
    publication_date = COALESCE($5, publication_date),
    content_path = COALESCE($6, content_path),
    current_version = COALESCE($7, current_version),
    cover_path = COALESCE($8, cover_path),
    document_type_id = COALESCE($9, document_type_id),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at, cover_path, document_type_id
`

type UpdateDocumentParams struct {
	ID              uuid.UUID
	Title           *string
	Description     *string
	CategoryID      *int32
	PublicationDate pgtype.Date
	ContentPath     *string
	CurrentVersion  *int32
	CoverPath       *string
	DocumentTypeID  *int32
}

// UpdateDocument
//
//	UPDATE documents
//	SET
//	    title = COALESCE($2, title),
//	    description = COALESCE($3, description),
//	    category_id = COALESCE($4, category_id),
//	    publication_date = COALESCE($5, publication_date),
//	    content_path = COALESCE($6, content_path),
//	    current_version = COALESCE($7, current_version),
//	    cover_path = COALESCE($8, cover_path),
//	    document_type_id = COALESCE($9, document_type_id),
//	    updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, title, description, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at, cover_path, document_type_id
func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.PublicationDate,
		arg.ContentPath,
		arg.CurrentVersion,
		arg.CoverPath,
		arg.DocumentTypeID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.PublicationDate,
		&i.ContentPath,
		&i.CurrentVersion,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CoverPath,
		&i.DocumentTypeID,
	)
	return i, err
}

const updateDocumentIndexed = `-- name: UpdateDocumentIndexed :exec
UPDATE documents
SET indexed = $2
WHERE id = $1
`

type UpdateDocumentIndexedParams struct {
	ID      uuid.UUID
	Indexed bool
}

// UpdateDocumentIndexed
//
//	UPDATE documents
//	SET indexed = $2
//	WHERE id = $1
func (q *Queries) UpdateDocumentIndexed(ctx context.Context, arg UpdateDocumentIndexedParams) error {
	_, err := q.db.Exec(ctx, updateDocumentIndexed, arg.ID, arg.Indexed)
	return err
}
