// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addDocumentTag = `-- name: AddDocumentTag :exec
INSERT INTO document_tags (document_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDocumentTagParams struct {
	DocumentID uuid.UUID
	TagID      int32
}

// AddDocumentTag
//
//	INSERT INTO document_tags (document_id, tag_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) AddDocumentTag(ctx context.Context, arg AddDocumentTagParams) error {
	_, err := q.db.Exec(ctx, addDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const clearDocumentTags = `-- name: ClearDocumentTags :exec
DELETE FROM document_tags
WHERE document_id = $1
`

// ClearDocumentTags
//
//	DELETE FROM document_tags
//	WHERE document_id = $1
func (q *Queries) ClearDocumentTags(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDocumentTags, documentID)
	return err
}

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents
WHERE (
    CASE
        WHEN $1::uuid IS NOT NULL THEN author_id = $1::uuid
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $2::int IS NOT NULL THEN category_id = $2::int
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $3::text IS NOT NULL AND $3::text != ''
        THEN to_tsvector('russian', title || ' ' || COALESCE(description, '')) @@ plainto_tsquery('russian', $3::text)
        ELSE TRUE
    END
)
`

type CountDocumentsParams struct {
	AuthorID   *uuid.UUID
	CategoryID *int32
	Search     *string
}

// CountDocuments
//
//	SELECT COUNT(*) FROM documents
//	WHERE (
//	    CASE
//	        WHEN $1::uuid IS NOT NULL THEN author_id = $1::uuid
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $2::int IS NOT NULL THEN category_id = $2::int
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $3::text IS NOT NULL AND $3::text != ''
//	        THEN to_tsvector('russian', title || ' ' || COALESCE(description, '')) @@ plainto_tsquery('russian', $3::text)
//	        ELSE TRUE
//	    END
//	)
func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments, arg.AuthorID, arg.CategoryID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio)
VALUES ($1, $2)
RETURNING id, name, bio, created_at, updated_at
`

type CreateAuthorParams struct {
	Name string
	Bio  *string
}

// CreateAuthor
//
//	INSERT INTO authors (name, bio)
//	VALUES ($1, $2)
//	RETURNING id, name, bio, created_at, updated_at
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at
`

type CreateCategoryParams struct {
	Title       string
	Description *string
}

// CreateCategory
//
//	INSERT INTO categories (title, description)
//	VALUES ($1, $2)
//	RETURNING id, title, description, created_at
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Title, arg.Description)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    title,
    description,
    author_id,
    category_id,
    publication_date,
    content_path,
    current_version
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at
`

type CreateDocumentParams struct {
	Title           string
	Description     *string
	AuthorID        uuid.UUID
	CategoryID      int32
	PublicationDate pgtype.Date
	ContentPath     string
	CurrentVersion  int32
}

// CreateDocument
//
//	INSERT INTO documents (
//	    title,
//	    description,
//	    author_id,
//	    category_id,
//	    publication_date,
//	    content_path,
//	    current_version
//	) VALUES ($1, $2, $3, $4, $5, $6, $7)
//	RETURNING id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at
func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.CategoryID,
		arg.PublicationDate,
		arg.ContentPath,
		arg.CurrentVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublicationDate,
		&i.ContentPath,
		&i.CurrentVersion,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
    document_id,
    version,
    content_path,
    changes,
    created_by
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, version, content_path, changes, created_by, created_at
`

type CreateDocumentVersionParams struct {
	DocumentID  uuid.UUID
	Version     int32
	ContentPath string
	Changes     *string
	CreatedBy   *uuid.UUID
}

// CreateDocumentVersion
//
//	INSERT INTO document_versions (
//	    document_id,
//	    version,
//	    content_path,
//	    changes,
//	    created_by
//	) VALUES ($1, $2, $3, $4, $5)
//	RETURNING id, document_id, version, content_path, changes, created_by, created_at
func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.Version,
		arg.ContentPath,
		arg.Changes,
		arg.CreatedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ContentPath,
		&i.Changes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (title)
VALUES ($1)
RETURNING id, title, created_at
`

// CreateTag
//
//	INSERT INTO tags (title)
//	VALUES ($1)
//	RETURNING id, title, created_at
func (q *Queries) CreateTag(ctx context.Context, title string) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, title)
	var i Tag
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

// DeleteDocument
//
//	DELETE FROM documents
//	WHERE id = $1
func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, bio, created_at, updated_at FROM authors
WHERE id = $1
`

// GetAuthorByID
//
//	SELECT id, name, bio, created_at, updated_at FROM authors
//	WHERE id = $1
func (q *Queries) GetAuthorByID(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, title, description, created_at FROM categories
WHERE id = $1
`

// GetCategoryByID
//
//	SELECT id, title, description, created_at FROM categories
//	WHERE id = $1
func (q *Queries) GetCategoryByID(ctx context.Context, id int32) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at FROM documents
WHERE id = $1
`

// GetDocumentByID
//
//	SELECT id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at FROM documents
//	WHERE id = $1
func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublicationDate,
		&i.ContentPath,
		&i.CurrentVersion,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentTags = `-- name: GetDocumentTags :many
SELECT t.id, t.title, t.created_at FROM tags t
INNER JOIN document_tags dt ON dt.tag_id = t.id
WHERE dt.document_id = $1
ORDER BY t.title
`

// GetDocumentTags
//
//	SELECT t.id, t.title, t.created_at FROM tags t
//	INNER JOIN document_tags dt ON dt.tag_id = t.id
//	WHERE dt.document_id = $1
//	ORDER BY t.title
func (q *Queries) GetDocumentTags(ctx context.Context, documentID uuid.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
WHERE document_id = $1 AND version = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID
	Version    int32
}

// GetDocumentVersion
//
//	SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
//	WHERE document_id = $1 AND version = $2
func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.ContentPath,
		&i.Changes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, title, created_at FROM tags
WHERE id = $1
`

// GetTagByID
//
//	SELECT id, title, created_at FROM tags
//	WHERE id = $1
func (q *Queries) GetTagByID(ctx context.Context, id int32) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, created_at, updated_at FROM authors
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListAuthorsParams struct {
	Limit  int32
	Offset int32
}

// ListAuthors
//
//	SELECT id, name, bio, created_at, updated_at FROM authors
//	ORDER BY name
//	LIMIT $1 OFFSET $2
func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, title, description, created_at FROM categories
ORDER BY title
`

// ListCategories
//
//	SELECT id, title, description, created_at FROM categories
//	ORDER BY title
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
WHERE document_id = $1
ORDER BY version DESC
`

// ListDocumentVersions
//
//	SELECT id, document_id, version, content_path, changes, created_by, created_at FROM document_versions
//	WHERE document_id = $1
//	ORDER BY version DESC
func (q *Queries) ListDocumentVersions(ctx context.Context, documentID uuid.UUID) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.ContentPath,
			&i.Changes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at FROM documents
WHERE (
    CASE
        WHEN $3::uuid IS NOT NULL THEN author_id = $3::uuid
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $4::int IS NOT NULL THEN category_id = $4::int
        ELSE TRUE
    END
) AND (
    CASE
        WHEN $5::text IS NOT NULL AND $5::text != ''
        THEN to_tsvector('russian', title || ' ' || COALESCE(description, '')) @@ plainto_tsquery('russian', $5::text)
        ELSE TRUE
    END
)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit      int32
	Offset     int32
	AuthorID   *uuid.UUID
	CategoryID *int32
	Search     *string
}

// ListDocuments
//
//	SELECT id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at FROM documents
//	WHERE (
//	    CASE
//	        WHEN $3::uuid IS NOT NULL THEN author_id = $3::uuid
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $4::int IS NOT NULL THEN category_id = $4::int
//	        ELSE TRUE
//	    END
//	) AND (
//	    CASE
//	        WHEN $5::text IS NOT NULL AND $5::text != ''
//	        THEN to_tsvector('russian', title || ' ' || COALESCE(description, '')) @@ plainto_tsquery('russian', $5::text)
//	        ELSE TRUE
//	    END
//	)
//	ORDER BY created_at DESC
//	LIMIT $1 OFFSET $2
func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.Limit,
		arg.Offset,
		arg.AuthorID,
		arg.CategoryID,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublicationDate,
			&i.ContentPath,
			&i.CurrentVersion,
			&i.Indexed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, title, created_at FROM tags
ORDER BY title
`

// ListTags
//
//	SELECT id, title, created_at FROM tags
//	ORDER BY title
func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDocumentTag = `-- name: RemoveDocumentTag :exec
DELETE FROM document_tags
WHERE document_id = $1 AND tag_id = $2
`

type RemoveDocumentTagParams struct {
	DocumentID uuid.UUID
	TagID      int32
}

// RemoveDocumentTag
//
//	DELETE FROM document_tags
//	WHERE document_id = $1 AND tag_id = $2
func (q *Queries) RemoveDocumentTag(ctx context.Context, arg RemoveDocumentTagParams) error {
	_, err := q.db.Exec(ctx, removeDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    author_id = COALESCE($4, author_id),
    category_id = COALESCE($5, category_id),
    publication_date = COALESCE($6, publication_date),
    content_path = COALESCE($7, content_path),
    current_version = COALESCE($8, current_version),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at
`

type UpdateDocumentParams struct {
	ID              uuid.UUID
	Title           *string
	Description     *string
	AuthorID        *uuid.UUID
	CategoryID      *int32
	PublicationDate pgtype.Date
	ContentPath     *string
	CurrentVersion  *int32
}

// UpdateDocument
//
//	UPDATE documents
//	SET
//	    title = COALESCE($2, title),
//	    description = COALESCE($3, description),
//	    author_id = COALESCE($4, author_id),
//	    category_id = COALESCE($5, category_id),
//	    publication_date = COALESCE($6, publication_date),
//	    content_path = COALESCE($7, content_path),
//	    current_version = COALESCE($8, current_version),
//	    updated_at = NOW()
//	WHERE id = $1
//	RETURNING id, title, description, author_id, category_id, publication_date, content_path, current_version, indexed, created_at, updated_at
func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorID,
		arg.CategoryID,
		arg.PublicationDate,
		arg.ContentPath,
		arg.CurrentVersion,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublicationDate,
		&i.ContentPath,
		&i.CurrentVersion,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentIndexed = `-- name: UpdateDocumentIndexed :exec
UPDATE documents
SET indexed = $2
WHERE id = $1
`

type UpdateDocumentIndexedParams struct {
	ID      uuid.UUID
	Indexed bool
}

// UpdateDocumentIndexed
//
//	UPDATE documents
//	SET indexed = $2
//	WHERE id = $1
func (q *Queries) UpdateDocumentIndexed(ctx context.Context, arg UpdateDocumentIndexedParams) error {
	_, err := q.db.Exec(ctx, updateDocumentIndexed, arg.ID, arg.Indexed)
	return err
}
