// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"

	"github.com/artmexbet/raibecas/services/auth/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIUserRepository creates a new instance of MockIUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserRepository {
	mock := &MockIUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserRepository is an autogenerated mock type for the IUserRepository type
type MockIUserRepository struct {
	mock.Mock
}

type MockIUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserRepository) EXPECT() *MockIUserRepository_Expecter {
	return &MockIUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) Create(ctx context.Context, user *domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *MockIUserRepository_Expecter) Create(ctx interface{}, user interface{}) *MockIUserRepository_Create_Call {
	return &MockIUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockIUserRepository_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *MockIUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_Create_Call) Return(err error) *MockIUserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user *domain.User) error) *MockIUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockIUserRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIUserRepository_Expecter) ExistsByEmail(ctx interface{}, email interface{}) *MockIUserRepository_ExistsByEmail_Call {
	return &MockIUserRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockIUserRepository_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIUserRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_ExistsByEmail_Call) Return(b bool, err error) *MockIUserRepository_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIUserRepository_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockIUserRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsername provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsername")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_ExistsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsername'
type MockIUserRepository_ExistsByUsername_Call struct {
	*mock.Call
}

// ExistsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) ExistsByUsername(ctx interface{}, username interface{}) *MockIUserRepository_ExistsByUsername_Call {
	return &MockIUserRepository_ExistsByUsername_Call{Call: _e.mock.On("ExistsByUsername", ctx, username)}
}

func (_c *MockIUserRepository_ExistsByUsername_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_ExistsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_ExistsByUsername_Call) Return(b bool, err error) *MockIUserRepository_ExistsByUsername_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIUserRepository_ExistsByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (bool, error)) *MockIUserRepository_ExistsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockIUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockIUserRepository_GetByEmail_Call {
	return &MockIUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockIUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByEmail_Call) Return(user *domain.User, err error) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockIUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIUserRepository_GetByID_Call {
	return &MockIUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIUserRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByID_Call) Return(user *domain.User, err error) *MockIUserRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.User, error)) *MockIUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) GetByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockIUserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockIUserRepository_Expecter) GetByUsername(ctx interface{}, username interface{}) *MockIUserRepository_GetByUsername_Call {
	return &MockIUserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *MockIUserRepository_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *MockIUserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserRepository_GetByUsername_Call) Return(user *domain.User, err error) *MockIUserRepository_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserRepository_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockIUserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockIUserRepository
func (_mock *MockIUserRepository) UpdatePassword(ctx context.Context, userID uuid.UUID, passwordHash string) error {
	ret := _mock.Called(ctx, userID, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, passwordHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockIUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - passwordHash string
func (_e *MockIUserRepository_Expecter) UpdatePassword(ctx interface{}, userID interface{}, passwordHash interface{}) *MockIUserRepository_UpdatePassword_Call {
	return &MockIUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, userID, passwordHash)}
}

func (_c *MockIUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, userID uuid.UUID, passwordHash string)) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIUserRepository_UpdatePassword_Call) Return(err error) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIUserRepository_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, passwordHash string) error) *MockIUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITokenStore creates a new instance of MockITokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITokenStore {
	mock := &MockITokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITokenStore is an autogenerated mock type for the ITokenStore type
type MockITokenStore struct {
	mock.Mock
}

type MockITokenStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITokenStore) EXPECT() *MockITokenStore_Expecter {
	return &MockITokenStore_Expecter{mock: &_m.Mock}
}

// DeleteAllRefreshTokens provides a mock function for the type MockITokenStore
func (_mock *MockITokenStore) DeleteAllRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllRefreshTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITokenStore_DeleteAllRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllRefreshTokens'
type MockITokenStore_DeleteAllRefreshTokens_Call struct {
	*mock.Call
}

// DeleteAllRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockITokenStore_Expecter) DeleteAllRefreshTokens(ctx interface{}, userID interface{}) *MockITokenStore_DeleteAllRefreshTokens_Call {
	return &MockITokenStore_DeleteAllRefreshTokens_Call{Call: _e.mock.On("DeleteAllRefreshTokens", ctx, userID)}
}

func (_c *MockITokenStore_DeleteAllRefreshTokens_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockITokenStore_DeleteAllRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITokenStore_DeleteAllRefreshTokens_Call) Return(err error) *MockITokenStore_DeleteAllRefreshTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITokenStore_DeleteAllRefreshTokens_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockITokenStore_DeleteAllRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockITokenStore
func (_mock *MockITokenStore) DeleteRefreshToken(ctx context.Context, userID uuid.UUID, tokenValue string) error {
	ret := _mock.Called(ctx, userID, tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, tokenValue)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITokenStore_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockITokenStore_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenValue string
func (_e *MockITokenStore_Expecter) DeleteRefreshToken(ctx interface{}, userID interface{}, tokenValue interface{}) *MockITokenStore_DeleteRefreshToken_Call {
	return &MockITokenStore_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, userID, tokenValue)}
}

func (_c *MockITokenStore_DeleteRefreshToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenValue string)) *MockITokenStore_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITokenStore_DeleteRefreshToken_Call) Return(err error) *MockITokenStore_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITokenStore_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tokenValue string) error) *MockITokenStore_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByValue provides a mock function for the type MockITokenStore
func (_mock *MockITokenStore) GetRefreshTokenByValue(ctx context.Context, tokenValue string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByValue")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenValue)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenValue)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITokenStore_GetRefreshTokenByValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByValue'
type MockITokenStore_GetRefreshTokenByValue_Call struct {
	*mock.Call
}

// GetRefreshTokenByValue is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenValue string
func (_e *MockITokenStore_Expecter) GetRefreshTokenByValue(ctx interface{}, tokenValue interface{}) *MockITokenStore_GetRefreshTokenByValue_Call {
	return &MockITokenStore_GetRefreshTokenByValue_Call{Call: _e.mock.On("GetRefreshTokenByValue", ctx, tokenValue)}
}

func (_c *MockITokenStore_GetRefreshTokenByValue_Call) Run(run func(ctx context.Context, tokenValue string)) *MockITokenStore_GetRefreshTokenByValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITokenStore_GetRefreshTokenByValue_Call) Return(refreshToken *domain.RefreshToken, err error) *MockITokenStore_GetRefreshTokenByValue_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockITokenStore_GetRefreshTokenByValue_Call) RunAndReturn(run func(ctx context.Context, tokenValue string) (*domain.RefreshToken, error)) *MockITokenStore_GetRefreshTokenByValue_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function for the type MockITokenStore
func (_mock *MockITokenStore) StoreRefreshToken(ctx context.Context, token *domain.RefreshToken, ttl time.Duration) error {
	ret := _mock.Called(ctx, token, ttl)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken, time.Duration) error); ok {
		r0 = returnFunc(ctx, token, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITokenStore_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type MockITokenStore_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
//   - ttl time.Duration
func (_e *MockITokenStore_Expecter) StoreRefreshToken(ctx interface{}, token interface{}, ttl interface{}) *MockITokenStore_StoreRefreshToken_Call {
	return &MockITokenStore_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, token, ttl)}
}

func (_c *MockITokenStore_StoreRefreshToken_Call) Run(run func(ctx context.Context, token *domain.RefreshToken, ttl time.Duration)) *MockITokenStore_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*domain.RefreshToken)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITokenStore_StoreRefreshToken_Call) Return(err error) *MockITokenStore_StoreRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITokenStore_StoreRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token *domain.RefreshToken, ttl time.Duration) error) *MockITokenStore_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistrationRepository creates a new instance of MockRegistrationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistrationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistrationRepository {
	mock := &MockRegistrationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistrationRepository is an autogenerated mock type for the RegistrationRepository type
type MockRegistrationRepository struct {
	mock.Mock
}

type MockRegistrationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistrationRepository) EXPECT() *MockRegistrationRepository_Expecter {
	return &MockRegistrationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRegistrationRepository
func (_mock *MockRegistrationRepository) Create(ctx context.Context, req *domain.RegistrationRequest) (uuid.UUID, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RegistrationRequest) (uuid.UUID, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RegistrationRequest) uuid.UUID); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.RegistrationRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistrationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRegistrationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.RegistrationRequest
func (_e *MockRegistrationRepository_Expecter) Create(ctx interface{}, req interface{}) *MockRegistrationRepository_Create_Call {
	return &MockRegistrationRepository_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *MockRegistrationRepository_Create_Call) Run(run func(ctx context.Context, req *domain.RegistrationRequest)) *MockRegistrationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RegistrationRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.RegistrationRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistrationRepository_Create_Call) Return(uUID uuid.UUID, err error) *MockRegistrationRepository_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockRegistrationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, req *domain.RegistrationRequest) (uuid.UUID, error)) *MockRegistrationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByEmail provides a mock function for the type MockRegistrationRepository
func (_mock *MockRegistrationRepository) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistrationRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockRegistrationRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRegistrationRepository_Expecter) ExistsByEmail(ctx interface{}, email interface{}) *MockRegistrationRepository_ExistsByEmail_Call {
	return &MockRegistrationRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", ctx, email)}
}

func (_c *MockRegistrationRepository_ExistsByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRegistrationRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistrationRepository_ExistsByEmail_Call) Return(b bool, err error) *MockRegistrationRepository_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRegistrationRepository_ExistsByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (bool, error)) *MockRegistrationRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsername provides a mock function for the type MockRegistrationRepository
func (_mock *MockRegistrationRepository) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsername")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistrationRepository_ExistsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsername'
type MockRegistrationRepository_ExistsByUsername_Call struct {
	*mock.Call
}

// ExistsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockRegistrationRepository_Expecter) ExistsByUsername(ctx interface{}, username interface{}) *MockRegistrationRepository_ExistsByUsername_Call {
	return &MockRegistrationRepository_ExistsByUsername_Call{Call: _e.mock.On("ExistsByUsername", ctx, username)}
}

func (_c *MockRegistrationRepository_ExistsByUsername_Call) Run(run func(ctx context.Context, username string)) *MockRegistrationRepository_ExistsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistrationRepository_ExistsByUsername_Call) Return(b bool, err error) *MockRegistrationRepository_ExistsByUsername_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRegistrationRepository_ExistsByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (bool, error)) *MockRegistrationRepository_ExistsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRegistrationRepository
func (_mock *MockRegistrationRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.RegistrationRequest, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.RegistrationRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.RegistrationRequest, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.RegistrationRequest); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RegistrationRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistrationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRegistrationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRegistrationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRegistrationRepository_GetByID_Call {
	return &MockRegistrationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRegistrationRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRegistrationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistrationRepository_GetByID_Call) Return(registrationRequest *domain.RegistrationRequest, err error) *MockRegistrationRepository_GetByID_Call {
	_c.Call.Return(registrationRequest, err)
	return _c
}

func (_c *MockRegistrationRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.RegistrationRequest, error)) *MockRegistrationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRegistrationRepository
func (_mock *MockRegistrationRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.RegistrationStatus, approvedBy *uuid.UUID) error {
	ret := _mock.Called(ctx, id, status, approvedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.RegistrationStatus, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, status, approvedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistrationRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRegistrationRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status domain.RegistrationStatus
//   - approvedBy *uuid.UUID
func (_e *MockRegistrationRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, approvedBy interface{}) *MockRegistrationRepository_UpdateStatus_Call {
	return &MockRegistrationRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, approvedBy)}
}

func (_c *MockRegistrationRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status domain.RegistrationStatus, approvedBy *uuid.UUID)) *MockRegistrationRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.RegistrationStatus
		if args[2] != nil {
			arg2 = args[2].(domain.RegistrationStatus)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRegistrationRepository_UpdateStatus_Call) Return(err error) *MockRegistrationRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistrationRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status domain.RegistrationStatus, approvedBy *uuid.UUID) error) *MockRegistrationRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
