// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package connector

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector(in *jlexer.Lexer, out *UpdateUserUpdates) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Email = string(in.String())
				}
			}
		case "username":
			if in.IsNull() {
				in.Skip()
				out.Username = nil
			} else {
				if out.Username == nil {
					out.Username = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Username = string(in.String())
				}
			}
		case "full_name":
			if in.IsNull() {
				in.Skip()
				out.FullName = nil
			} else {
				if out.FullName == nil {
					out.FullName = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.FullName = string(in.String())
				}
			}
		case "is_active":
			if in.IsNull() {
				in.Skip()
				out.IsActive = nil
			} else {
				if out.IsActive == nil {
					out.IsActive = new(bool)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.IsActive = bool(in.Bool())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector(out *jwriter.Writer, in UpdateUserUpdates) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Email != nil {
		const prefix string = ",\"email\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Email))
	}
	if in.Username != nil {
		const prefix string = ",\"username\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Username))
	}
	if in.FullName != nil {
		const prefix string = ",\"full_name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.FullName))
	}
	if in.IsActive != nil {
		const prefix string = ",\"is_active\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(*in.IsActive))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateUserUpdates) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateUserUpdates) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateUserUpdates) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateUserUpdates) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector1(in *jlexer.Lexer, out *UpdateUserRequestWrapper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		case "updates":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Updates).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector1(out *jwriter.Writer, in UpdateUserRequestWrapper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"updates\":"
		out.RawString(prefix)
		(in.Updates).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateUserRequestWrapper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateUserRequestWrapper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateUserRequestWrapper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateUserRequestWrapper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector1(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector2(in *jlexer.Lexer, out *UpdateDocumentRequestWrapper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "updates":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Updates = make(map[string]interface{})
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 interface{}
					if m, ok := v1.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v1.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v1 = in.Interface()
					}
					(out.Updates)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector2(out *jwriter.Writer, in UpdateDocumentRequestWrapper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"updates\":"
		out.RawString(prefix)
		if in.Updates == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Updates {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if m, ok := v2Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v2Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v2Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateDocumentRequestWrapper) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateDocumentRequestWrapper) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateDocumentRequestWrapper) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateDocumentRequestWrapper) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector2(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector3(in *jlexer.Lexer, out *RejectRegistrationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.RequestID).UnmarshalText(data))
				}
			}
		case "approver_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ApproverID).UnmarshalText(data))
				}
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector3(out *jwriter.Writer, in RejectRegistrationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.RequestID).MarshalText())
	}
	{
		const prefix string = ",\"approver_id\":"
		out.RawString(prefix)
		out.RawText((in.ApproverID).MarshalText())
	}
	if in.Reason != "" {
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RejectRegistrationRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RejectRegistrationRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RejectRegistrationRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RejectRegistrationRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector3(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector4(in *jlexer.Lexer, out *LogoutRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "token_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenID = string(in.String())
			}
		case "access_token_jti":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccessTokenJTI = string(in.String())
			}
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.UserID).UnmarshalText(data))
				}
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector4(out *jwriter.Writer, in LogoutRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"token_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.TokenID))
	}
	{
		const prefix string = ",\"access_token_jti\":"
		out.RawString(prefix)
		out.String(string(in.AccessTokenJTI))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LogoutRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LogoutRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LogoutRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LogoutRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector4(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector5(in *jlexer.Lexer, out *LogoutAllRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.UserID).UnmarshalText(data))
				}
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector5(out *jwriter.Writer, in LogoutAllRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LogoutAllRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LogoutAllRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LogoutAllRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LogoutAllRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector5(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector6(in *jlexer.Lexer, out *GetDocumentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector6(out *jwriter.Writer, in GetDocumentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetDocumentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetDocumentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetDocumentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetDocumentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector6(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector7(in *jlexer.Lexer, out *DeleteUserRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector7(out *jwriter.Writer, in DeleteUserRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteUserRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteUserRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteUserRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteUserRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector7(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector8(in *jlexer.Lexer, out *DeleteDocumentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector8(out *jwriter.Writer, in DeleteDocumentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeleteDocumentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeleteDocumentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeleteDocumentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeleteDocumentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector8(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector9(in *jlexer.Lexer, out *ChangePasswordRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.UserID).UnmarshalText(data))
				}
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "old_password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OldPassword = string(in.String())
			}
		case "new_password":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NewPassword = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector9(out *jwriter.Writer, in ChangePasswordRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.UserID).MarshalText())
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"old_password\":"
		out.RawString(prefix)
		out.String(string(in.OldPassword))
	}
	{
		const prefix string = ",\"new_password\":"
		out.RawString(prefix)
		out.String(string(in.NewPassword))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangePasswordRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangePasswordRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangePasswordRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangePasswordRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector9(l, v)
}
func easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector10(in *jlexer.Lexer, out *ApproveRegistrationRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "request_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.RequestID).UnmarshalText(data))
				}
			}
		case "approver_id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ApproverID).UnmarshalText(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector10(out *jwriter.Writer, in ApproveRegistrationRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.RawText((in.RequestID).MarshalText())
	}
	{
		const prefix string = ",\"approver_id\":"
		out.RawString(prefix)
		out.RawText((in.ApproverID).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApproveRegistrationRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApproveRegistrationRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4fb26656EncodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApproveRegistrationRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApproveRegistrationRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4fb26656DecodeGithubComArtmexbetRaibecasServicesGatewayInternalConnector10(l, v)
}
