// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	uuid "github.com/google/uuid"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(in *jlexer.Lexer, out *UpdateDocumentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "document":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Document).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(out *jwriter.Writer, in UpdateDocumentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"document\":"
		out.RawString(prefix[1:])
		(in.Document).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateDocumentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateDocumentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateDocumentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateDocumentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(in *jlexer.Lexer, out *UpdateDocumentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Title = string(in.String())
				}
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "authorId":
			if in.IsNull() {
				in.Skip()
				out.AuthorID = nil
			} else {
				if out.AuthorID == nil {
					out.AuthorID = new(uuid.UUID)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.UnsafeBytes(); in.Ok() {
						in.AddError((*out.AuthorID).UnmarshalText(data))
					}
				}
			}
		case "categoryId":
			if in.IsNull() {
				in.Skip()
				out.CategoryID = nil
			} else {
				if out.CategoryID == nil {
					out.CategoryID = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.CategoryID = int(in.Int())
				}
			}
		case "publicationDate":
			if in.IsNull() {
				in.Skip()
				out.PublicationDate = nil
			} else {
				if out.PublicationDate == nil {
					out.PublicationDate = new(time.Time)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.PublicationDate).UnmarshalJSON(data))
					}
				}
			}
		case "tagIds":
			if in.IsNull() {
				in.Skip()
				out.TagIDs = nil
			} else {
				in.Delim('[')
				if out.TagIDs == nil {
					if !in.IsDelim(']') {
						out.TagIDs = make([]int, 0, 8)
					} else {
						out.TagIDs = []int{}
					}
				} else {
					out.TagIDs = (out.TagIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = int(in.Int())
					}
					out.TagIDs = append(out.TagIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(out *jwriter.Writer, in UpdateDocumentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		if in.Title == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Title))
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"authorId\":"
		out.RawString(prefix)
		if in.AuthorID == nil {
			out.RawString("null")
		} else {
			out.RawText((*in.AuthorID).MarshalText())
		}
	}
	{
		const prefix string = ",\"categoryId\":"
		out.RawString(prefix)
		if in.CategoryID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.CategoryID))
		}
	}
	{
		const prefix string = ",\"publicationDate\":"
		out.RawString(prefix)
		if in.PublicationDate == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.PublicationDate).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"tagIds\":"
		out.RawString(prefix)
		if in.TagIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.TagIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateDocumentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateDocumentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateDocumentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateDocumentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(in *jlexer.Lexer, out *ListDocumentsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "documents":
			if in.IsNull() {
				in.Skip()
				out.Documents = nil
			} else {
				in.Delim('[')
				if out.Documents == nil {
					if !in.IsDelim(']') {
						out.Documents = make([]Document, 0, 0)
					} else {
						out.Documents = []Document{}
					}
				} else {
					out.Documents = (out.Documents)[:0]
				}
				for !in.IsDelim(']') {
					var v4 Document
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					out.Documents = append(out.Documents, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "page":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Page = int(in.Int())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "totalPages":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalPages = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(out *jwriter.Writer, in ListDocumentsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"documents\":"
		out.RawString(prefix[1:])
		if in.Documents == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Documents {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"page\":"
		out.RawString(prefix)
		out.Int(int(in.Page))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"totalPages\":"
		out.RawString(prefix)
		out.Int(int(in.TotalPages))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListDocumentsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListDocumentsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListDocumentsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListDocumentsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(in *jlexer.Lexer, out *ListDocumentsQuery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Page":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Page = int(in.Int())
			}
		case "Limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "AuthorID":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.AuthorID).UnmarshalText(data))
				}
			}
		case "CategoryID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "TagID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TagID = int(in.Int())
			}
		case "Search":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Search = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(out *jwriter.Writer, in ListDocumentsQuery) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Page\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Page))
	}
	{
		const prefix string = ",\"Limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"AuthorID\":"
		out.RawString(prefix)
		out.RawText((in.AuthorID).MarshalText())
	}
	{
		const prefix string = ",\"CategoryID\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"TagID\":"
		out.RawString(prefix)
		out.Int(int(in.TagID))
	}
	{
		const prefix string = ",\"Search\":"
		out.RawString(prefix)
		out.String(string(in.Search))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListDocumentsQuery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListDocumentsQuery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListDocumentsQuery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListDocumentsQuery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(in *jlexer.Lexer, out *GetDocumentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "document":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Document).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(out *jwriter.Writer, in GetDocumentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"document\":"
		out.RawString(prefix[1:])
		(in.Document).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetDocumentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetDocumentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetDocumentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetDocumentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(in *jlexer.Lexer, out *CreateDocumentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "document":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Document).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(out *jwriter.Writer, in CreateDocumentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"document\":"
		out.RawString(prefix[1:])
		(in.Document).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateDocumentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateDocumentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateDocumentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateDocumentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(in *jlexer.Lexer, out *CreateDocumentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "authorId":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.AuthorID).UnmarshalText(data))
				}
			}
		case "categoryId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "publicationDate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.PublicationDate).UnmarshalJSON(data))
				}
			}
		case "tagIds":
			if in.IsNull() {
				in.Skip()
				out.TagIDs = nil
			} else {
				in.Delim('[')
				if out.TagIDs == nil {
					if !in.IsDelim(']') {
						out.TagIDs = make([]int, 0, 8)
					} else {
						out.TagIDs = []int{}
					}
				} else {
					out.TagIDs = (out.TagIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v7 int
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = int(in.Int())
					}
					out.TagIDs = append(out.TagIDs, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(out *jwriter.Writer, in CreateDocumentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	{
		const prefix string = ",\"authorId\":"
		out.RawString(prefix)
		out.RawText((in.AuthorID).MarshalText())
	}
	{
		const prefix string = ",\"categoryId\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"publicationDate\":"
		out.RawString(prefix)
		out.Raw((in.PublicationDate).MarshalJSON())
	}
	{
		const prefix string = ",\"tagIds\":"
		out.RawString(prefix)
		if in.TagIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.TagIDs {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateDocumentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateDocumentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateDocumentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateDocumentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(l, v)
}
