// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(in *jlexer.Lexer, out *UpdateDocumentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "document":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Document).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(out *jwriter.Writer, in UpdateDocumentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"document\":"
		out.RawString(prefix[1:])
		(in.Document).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateDocumentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateDocumentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateDocumentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateDocumentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(in *jlexer.Lexer, out *UpdateDocumentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.ID).UnmarshalText(data))
				}
			}
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Title = string(in.String())
				}
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "categoryId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "documentTypeId":
			if in.IsNull() {
				in.Skip()
				out.DocumentTypeID = nil
			} else {
				if out.DocumentTypeID == nil {
					out.DocumentTypeID = new(int)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.DocumentTypeID = int(in.Int())
				}
			}
		case "participants":
			if in.IsNull() {
				in.Skip()
				out.Participants = nil
			} else {
				in.Delim('[')
				if out.Participants == nil {
					if !in.IsDelim(']') {
						out.Participants = make([]DocumentParticipantRef, 0, 2)
					} else {
						out.Participants = []DocumentParticipantRef{}
					}
				} else {
					out.Participants = (out.Participants)[:0]
				}
				for !in.IsDelim(']') {
					var v1 DocumentParticipantRef
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Participants = append(out.Participants, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "publicationDate":
			if in.IsNull() {
				in.Skip()
				out.PublicationDate = nil
			} else {
				if out.PublicationDate == nil {
					out.PublicationDate = new(time.Time)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.PublicationDate).UnmarshalJSON(data))
					}
				}
			}
		case "tagIds":
			if in.IsNull() {
				in.Skip()
				out.TagIDs = nil
			} else {
				in.Delim('[')
				if out.TagIDs == nil {
					if !in.IsDelim(']') {
						out.TagIDs = make([]int, 0, 8)
					} else {
						out.TagIDs = []int{}
					}
				} else {
					out.TagIDs = (out.TagIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v2 int
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = int(in.Int())
					}
					out.TagIDs = append(out.TagIDs, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(out *jwriter.Writer, in UpdateDocumentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.RawText((in.ID).MarshalText())
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		if in.Title == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Title))
		}
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	if in.CategoryID != 0 {
		const prefix string = ",\"categoryId\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	if in.DocumentTypeID != nil {
		const prefix string = ",\"documentTypeId\":"
		out.RawString(prefix)
		out.Int(int(*in.DocumentTypeID))
	}
	if len(in.Participants) != 0 {
		const prefix string = ",\"participants\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v3, v4 := range in.Participants {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"publicationDate\":"
		out.RawString(prefix)
		if in.PublicationDate == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.PublicationDate).MarshalJSON())
		}
	}
	{
		const prefix string = ",\"tagIds\":"
		out.RawString(prefix)
		if in.TagIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.TagIDs {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateDocumentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateDocumentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateDocumentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateDocumentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain1(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(in *jlexer.Lexer, out *ListTagsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "tags":
			if in.IsNull() {
				in.Skip()
				out.Tags = nil
			} else {
				in.Delim('[')
				if out.Tags == nil {
					if !in.IsDelim(']') {
						out.Tags = make([]Tag, 0, 2)
					} else {
						out.Tags = []Tag{}
					}
				} else {
					out.Tags = (out.Tags)[:0]
				}
				for !in.IsDelim(']') {
					var v7 Tag
					if in.IsNull() {
						in.Skip()
					} else {
						(v7).UnmarshalEasyJSON(in)
					}
					out.Tags = append(out.Tags, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(out *jwriter.Writer, in ListTagsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tags\":"
		out.RawString(prefix[1:])
		if in.Tags == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Tags {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListTagsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListTagsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListTagsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListTagsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain2(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(in *jlexer.Lexer, out *ListDocumentsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "documents":
			if in.IsNull() {
				in.Skip()
				out.Documents = nil
			} else {
				in.Delim('[')
				if out.Documents == nil {
					if !in.IsDelim(']') {
						out.Documents = make([]Document, 0, 0)
					} else {
						out.Documents = []Document{}
					}
				} else {
					out.Documents = (out.Documents)[:0]
				}
				for !in.IsDelim(']') {
					var v10 Document
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.Documents = append(out.Documents, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		case "page":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Page = int(in.Int())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "totalPages":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TotalPages = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(out *jwriter.Writer, in ListDocumentsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"documents\":"
		out.RawString(prefix[1:])
		if in.Documents == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Documents {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"page\":"
		out.RawString(prefix)
		out.Int(int(in.Page))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"totalPages\":"
		out.RawString(prefix)
		out.Int(int(in.TotalPages))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListDocumentsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListDocumentsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListDocumentsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListDocumentsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain3(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(in *jlexer.Lexer, out *ListDocumentsQuery) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Page":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Page = int(in.Int())
			}
		case "Limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "AuthorID":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.UnsafeBytes(); in.Ok() {
					in.AddError((out.AuthorID).UnmarshalText(data))
				}
			}
		case "CategoryID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "DocumentTypeID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DocumentTypeID = int(in.Int())
			}
		case "TagID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TagID = int(in.Int())
			}
		case "Search":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Search = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(out *jwriter.Writer, in ListDocumentsQuery) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Page\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Page))
	}
	{
		const prefix string = ",\"Limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"AuthorID\":"
		out.RawString(prefix)
		out.RawText((in.AuthorID).MarshalText())
	}
	{
		const prefix string = ",\"CategoryID\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"DocumentTypeID\":"
		out.RawString(prefix)
		out.Int(int(in.DocumentTypeID))
	}
	{
		const prefix string = ",\"TagID\":"
		out.RawString(prefix)
		out.Int(int(in.TagID))
	}
	{
		const prefix string = ",\"Search\":"
		out.RawString(prefix)
		out.String(string(in.Search))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListDocumentsQuery) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListDocumentsQuery) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListDocumentsQuery) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListDocumentsQuery) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain4(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(in *jlexer.Lexer, out *ListDocumentTypesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "documentTypes":
			if in.IsNull() {
				in.Skip()
				out.DocumentTypes = nil
			} else {
				in.Delim('[')
				if out.DocumentTypes == nil {
					if !in.IsDelim(']') {
						out.DocumentTypes = make([]DocumentType, 0, 2)
					} else {
						out.DocumentTypes = []DocumentType{}
					}
				} else {
					out.DocumentTypes = (out.DocumentTypes)[:0]
				}
				for !in.IsDelim(']') {
					var v13 DocumentType
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.DocumentTypes = append(out.DocumentTypes, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(out *jwriter.Writer, in ListDocumentTypesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"documentTypes\":"
		out.RawString(prefix[1:])
		if in.DocumentTypes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.DocumentTypes {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListDocumentTypesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListDocumentTypesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListDocumentTypesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListDocumentTypesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain5(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(in *jlexer.Lexer, out *ListCategoriesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "categories":
			if in.IsNull() {
				in.Skip()
				out.Categories = nil
			} else {
				in.Delim('[')
				if out.Categories == nil {
					if !in.IsDelim(']') {
						out.Categories = make([]Category, 0, 2)
					} else {
						out.Categories = []Category{}
					}
				} else {
					out.Categories = (out.Categories)[:0]
				}
				for !in.IsDelim(']') {
					var v16 Category
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Categories = append(out.Categories, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(out *jwriter.Writer, in ListCategoriesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"categories\":"
		out.RawString(prefix[1:])
		if in.Categories == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Categories {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListCategoriesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListCategoriesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListCategoriesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListCategoriesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain6(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain7(in *jlexer.Lexer, out *ListAuthorshipTypesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "authorshipTypes":
			if in.IsNull() {
				in.Skip()
				out.AuthorshipTypes = nil
			} else {
				in.Delim('[')
				if out.AuthorshipTypes == nil {
					if !in.IsDelim(']') {
						out.AuthorshipTypes = make([]AuthorshipType, 0, 2)
					} else {
						out.AuthorshipTypes = []AuthorshipType{}
					}
				} else {
					out.AuthorshipTypes = (out.AuthorshipTypes)[:0]
				}
				for !in.IsDelim(']') {
					var v19 AuthorshipType
					if in.IsNull() {
						in.Skip()
					} else {
						(v19).UnmarshalEasyJSON(in)
					}
					out.AuthorshipTypes = append(out.AuthorshipTypes, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain7(out *jwriter.Writer, in ListAuthorshipTypesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"authorshipTypes\":"
		out.RawString(prefix[1:])
		if in.AuthorshipTypes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.AuthorshipTypes {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListAuthorshipTypesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListAuthorshipTypesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListAuthorshipTypesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListAuthorshipTypesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain7(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain8(in *jlexer.Lexer, out *ListAuthorsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "authors":
			if in.IsNull() {
				in.Skip()
				out.Authors = nil
			} else {
				in.Delim('[')
				if out.Authors == nil {
					if !in.IsDelim(']') {
						out.Authors = make([]Author, 0, 2)
					} else {
						out.Authors = []Author{}
					}
				} else {
					out.Authors = (out.Authors)[:0]
				}
				for !in.IsDelim(']') {
					var v22 Author
					if in.IsNull() {
						in.Skip()
					} else {
						(v22).UnmarshalEasyJSON(in)
					}
					out.Authors = append(out.Authors, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain8(out *jwriter.Writer, in ListAuthorsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"authors\":"
		out.RawString(prefix[1:])
		if in.Authors == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.Authors {
				if v23 > 0 {
					out.RawByte(',')
				}
				(v24).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListAuthorsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListAuthorsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListAuthorsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListAuthorsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain8(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain9(in *jlexer.Lexer, out *GetDocumentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "document":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Document).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain9(out *jwriter.Writer, in GetDocumentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"document\":"
		out.RawString(prefix[1:])
		(in.Document).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetDocumentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetDocumentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetDocumentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetDocumentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain9(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain10(in *jlexer.Lexer, out *CreateTagResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "tag":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Tag).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain10(out *jwriter.Writer, in CreateTagResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tag\":"
		out.RawString(prefix[1:])
		(in.Tag).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTagResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTagResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTagResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTagResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain10(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain11(in *jlexer.Lexer, out *CreateTagRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain11(out *jwriter.Writer, in CreateTagRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTagRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTagRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTagRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTagRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain11(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain12(in *jlexer.Lexer, out *CreateDocumentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "document":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Document).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain12(out *jwriter.Writer, in CreateDocumentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"document\":"
		out.RawString(prefix[1:])
		(in.Document).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateDocumentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateDocumentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateDocumentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateDocumentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain12(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain13(in *jlexer.Lexer, out *CreateDocumentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
				out.Description = nil
			} else {
				if out.Description == nil {
					out.Description = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Description = string(in.String())
				}
			}
		case "categoryId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CategoryID = int(in.Int())
			}
		case "documentTypeId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DocumentTypeID = int(in.Int())
			}
		case "participants":
			if in.IsNull() {
				in.Skip()
				out.Participants = nil
			} else {
				in.Delim('[')
				if out.Participants == nil {
					if !in.IsDelim(']') {
						out.Participants = make([]DocumentParticipantRef, 0, 2)
					} else {
						out.Participants = []DocumentParticipantRef{}
					}
				} else {
					out.Participants = (out.Participants)[:0]
				}
				for !in.IsDelim(']') {
					var v25 DocumentParticipantRef
					if in.IsNull() {
						in.Skip()
					} else {
						(v25).UnmarshalEasyJSON(in)
					}
					out.Participants = append(out.Participants, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "publicationDate":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.PublicationDate).UnmarshalJSON(data))
				}
			}
		case "tagIds":
			if in.IsNull() {
				in.Skip()
				out.TagIDs = nil
			} else {
				in.Delim('[')
				if out.TagIDs == nil {
					if !in.IsDelim(']') {
						out.TagIDs = make([]int, 0, 8)
					} else {
						out.TagIDs = []int{}
					}
				} else {
					out.TagIDs = (out.TagIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v26 int
					if in.IsNull() {
						in.Skip()
					} else {
						v26 = int(in.Int())
					}
					out.TagIDs = append(out.TagIDs, v26)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "content":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Content = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain13(out *jwriter.Writer, in CreateDocumentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		if in.Description == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Description))
		}
	}
	if in.CategoryID != 0 {
		const prefix string = ",\"categoryId\":"
		out.RawString(prefix)
		out.Int(int(in.CategoryID))
	}
	{
		const prefix string = ",\"documentTypeId\":"
		out.RawString(prefix)
		out.Int(int(in.DocumentTypeID))
	}
	{
		const prefix string = ",\"participants\":"
		out.RawString(prefix)
		if in.Participants == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v27, v28 := range in.Participants {
				if v27 > 0 {
					out.RawByte(',')
				}
				(v28).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"publicationDate\":"
		out.RawString(prefix)
		out.Raw((in.PublicationDate).MarshalJSON())
	}
	{
		const prefix string = ",\"tagIds\":"
		out.RawString(prefix)
		if in.TagIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.TagIDs {
				if v29 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v30))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix)
		out.String(string(in.Content))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateDocumentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateDocumentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateDocumentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateDocumentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain13(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain14(in *jlexer.Lexer, out *CreateCategoryResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "category":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Category).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain14(out *jwriter.Writer, in CreateCategoryResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		(in.Category).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCategoryResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCategoryResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCategoryResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCategoryResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain14(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain15(in *jlexer.Lexer, out *CreateCategoryRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain15(out *jwriter.Writer, in CreateCategoryRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCategoryRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCategoryRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCategoryRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCategoryRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain15(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain16(in *jlexer.Lexer, out *CreateAuthorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "author":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Author).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain16(out *jwriter.Writer, in CreateAuthorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix[1:])
		(in.Author).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAuthorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAuthorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAuthorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAuthorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain16(l, v)
}
func easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain17(in *jlexer.Lexer, out *CreateAuthorRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain17(out *jwriter.Writer, in CreateAuthorRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAuthorRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAuthorRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e528d04EncodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAuthorRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAuthorRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e528d04DecodeGithubComArtmexbetRaibecasServicesGatewayInternalDomain17(l, v)
}
